package main

import (
	"fmt"
	"strings"
)

func renderManifest(m manifest) string {
	var b strings.Builder
	b.WriteString("# Figma AI Agent Coverage\n\n")
	b.WriteString("<!-- Code generated by go run ./tools/figmacoverage render; DO NOT EDIT. -->\n\n")
	fmt.Fprintf(&b, "> Riido task: %s\n\n", cell(m.RiidoTask))
	b.WriteString("This projection is generated from `figma-ai-agent-coverage.riido.json`.\n")
	b.WriteString("Figma is evidence, not the durable SSOT for policy, API, daemon, or infra behavior.\n\n")
	renderSource(&b, m)
	renderPolicy(&b, m.CoveragePolicy)
	renderPages(&b, m.ExpectedPages)
	renderCoverageSummary(&b, m.Entries)
	renderEntries(&b, "UI Top-Level Coverage", m.Entries)
	renderEntryDetails(&b, m.Entries)
	renderAnnotationPolicy(&b, m.APIAnnotationContentPolicy)
	renderAnnotations(&b, m.APIGeneratedAnnotationInventory)
	renderResolvedAnnotations(&b, m.APIGeneratedAnnotations)
	renderEntries(&b, "Non-UI Coverage Decisions", m.NonUITopLevelNodes)
	renderEntryDetails(&b, m.NonUITopLevelNodes)
	renderEvidence(&b, m)
	return strings.TrimRight(b.String(), "\n") + "\n"
}
