package main

import (
	"strings"
	"testing"
)

func TestRenderManifestMarksGeneratedDoc(t *testing.T) {
	m := minimalManifest()
	body := renderManifest(m)
	if !strings.Contains(body, "Code generated by go run ./tools/figmacoverage render") {
		t.Fatalf("missing generated marker: %q", body)
	}
	if !strings.Contains(body, m.Figma.FileKey) {
		t.Fatalf("missing figma file key: %q", body)
	}
}
