// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package runstate

var runStateStringByCode = map[RunStateCode]RunStateString{
	RunStateCodePending:             RunStateStringPending,
	RunStateCodePreparing:           RunStateStringPreparing,
	RunStateCodeStartingProvider:    RunStateStringStartingProvider,
	RunStateCodeHandshaking:         RunStateStringHandshaking,
	RunStateCodeRunning:             RunStateStringRunning,
	RunStateCodeWaitingToolApproval: RunStateStringWaitingToolApproval,
	RunStateCodeToolRunning:         RunStateStringToolRunning,
	RunStateCodeWaitingProvider:     RunStateStringWaitingProvider,
	RunStateCodeCompleting:          RunStateStringCompleting,
	RunStateCodeCompleted:           RunStateStringCompleted,
	RunStateCodeFailed:              RunStateStringFailed,
	RunStateCodeCancelled:           RunStateStringCancelled,
	RunStateCodeTimedOut:            RunStateStringTimedOut,
	RunStateCodeIdleStopped:         RunStateStringIdleStopped,
}
