// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package runstate

func (value RunState) Code() RunStateCode {
	return ParseRunStateCode(string(value))
}

func ParseRunStateCode(value string) RunStateCode {
	code, ok := runStateCodeByString[RunStateString(value)]
	if !ok {
		return RunStateCodeUnknown
	}
	return code
}
