// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package runstate

func (code RunStateCode) IsTerminal() bool {
	switch code {
	case RunStateCodeCompleted, RunStateCodeFailed, RunStateCodeCancelled, RunStateCodeTimedOut, RunStateCodeIdleStopped:
		return true
	default:
		return false
	}
}

func (value RunState) IsTerminal() bool {
	return value.Code().IsTerminal()
}
