// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package runstate

var runStateCodeByString = map[RunStateString]RunStateCode{
	RunStateStringPending:             RunStateCodePending,
	RunStateStringPreparing:           RunStateCodePreparing,
	RunStateStringStartingProvider:    RunStateCodeStartingProvider,
	RunStateStringHandshaking:         RunStateCodeHandshaking,
	RunStateStringRunning:             RunStateCodeRunning,
	RunStateStringWaitingToolApproval: RunStateCodeWaitingToolApproval,
	RunStateStringToolRunning:         RunStateCodeToolRunning,
	RunStateStringWaitingProvider:     RunStateCodeWaitingProvider,
	RunStateStringCompleting:          RunStateCodeCompleting,
	RunStateStringCompleted:           RunStateCodeCompleted,
	RunStateStringFailed:              RunStateCodeFailed,
	RunStateStringCancelled:           RunStateCodeCancelled,
	RunStateStringTimedOut:            RunStateCodeTimedOut,
	RunStateStringIdleStopped:         RunStateCodeIdleStopped,
}
