// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package runstate

func (code RunStateCode) IsKnown() bool {
	_, ok := runStateStringByCode[code]
	return ok
}

func (code RunStateCode) StringValue() RunStateString {
	return runStateStringByCode[code]
}

func (code RunStateCode) String() string {
	return string(code.StringValue())
}

func (code RunStateCode) RunState() RunState {
	return RunState(code.StringValue())
}
