// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package runstate

type RunStateCode uint16

type RunStateString string

const (
	RunStateCodeUnknown RunStateCode = iota
	RunStateCodePending
	RunStateCodePreparing
	RunStateCodeStartingProvider
	RunStateCodeHandshaking
	RunStateCodeRunning
	RunStateCodeWaitingToolApproval
	RunStateCodeToolRunning
	RunStateCodeWaitingProvider
	RunStateCodeCompleting
	RunStateCodeCompleted
	RunStateCodeFailed
	RunStateCodeCancelled
	RunStateCodeTimedOut
	RunStateCodeIdleStopped
)

const (
	RunStateStringPending             RunStateString = "pending"
	RunStateStringPreparing           RunStateString = "preparing"
	RunStateStringStartingProvider    RunStateString = "starting_provider"
	RunStateStringHandshaking         RunStateString = "handshaking"
	RunStateStringRunning             RunStateString = "running"
	RunStateStringWaitingToolApproval RunStateString = "waiting_tool_approval"
	RunStateStringToolRunning         RunStateString = "tool_running"
	RunStateStringWaitingProvider     RunStateString = "waiting_provider"
	RunStateStringCompleting          RunStateString = "completing"
	RunStateStringCompleted           RunStateString = "completed"
	RunStateStringFailed              RunStateString = "failed"
	RunStateStringCancelled           RunStateString = "cancelled"
	RunStateStringTimedOut            RunStateString = "timed_out"
	RunStateStringIdleStopped         RunStateString = "idle_stopped"
)

const (
	StatePending             RunState = RunState(RunStateStringPending)
	StatePreparing           RunState = RunState(RunStateStringPreparing)
	StateStartingProvider    RunState = RunState(RunStateStringStartingProvider)
	StateHandshaking         RunState = RunState(RunStateStringHandshaking)
	StateRunning             RunState = RunState(RunStateStringRunning)
	StateWaitingToolApproval RunState = RunState(RunStateStringWaitingToolApproval)
	StateToolRunning         RunState = RunState(RunStateStringToolRunning)
	StateWaitingProvider     RunState = RunState(RunStateStringWaitingProvider)
	StateCompleting          RunState = RunState(RunStateStringCompleting)
	StateCompleted           RunState = RunState(RunStateStringCompleted)
	StateFailed              RunState = RunState(RunStateStringFailed)
	StateCancelled           RunState = RunState(RunStateStringCancelled)
	StateTimedOut            RunState = RunState(RunStateStringTimedOut)
	StateIdleStopped         RunState = RunState(RunStateStringIdleStopped)
)

func (value RunState) Code() RunStateCode {
	return ParseRunStateCode(string(value))
}

func ParseRunStateCode(value string) RunStateCode {
	switch RunStateString(value) {
	case RunStateStringPending:
		return RunStateCodePending
	case RunStateStringPreparing:
		return RunStateCodePreparing
	case RunStateStringStartingProvider:
		return RunStateCodeStartingProvider
	case RunStateStringHandshaking:
		return RunStateCodeHandshaking
	case RunStateStringRunning:
		return RunStateCodeRunning
	case RunStateStringWaitingToolApproval:
		return RunStateCodeWaitingToolApproval
	case RunStateStringToolRunning:
		return RunStateCodeToolRunning
	case RunStateStringWaitingProvider:
		return RunStateCodeWaitingProvider
	case RunStateStringCompleting:
		return RunStateCodeCompleting
	case RunStateStringCompleted:
		return RunStateCodeCompleted
	case RunStateStringFailed:
		return RunStateCodeFailed
	case RunStateStringCancelled:
		return RunStateCodeCancelled
	case RunStateStringTimedOut:
		return RunStateCodeTimedOut
	case RunStateStringIdleStopped:
		return RunStateCodeIdleStopped
	default:
		return RunStateCodeUnknown
	}
}

func (code RunStateCode) IsKnown() bool {
	return code >= RunStateCodePending && code <= RunStateCodeIdleStopped
}

func (code RunStateCode) StringValue() RunStateString {
	switch code {
	case RunStateCodePending:
		return RunStateStringPending
	case RunStateCodePreparing:
		return RunStateStringPreparing
	case RunStateCodeStartingProvider:
		return RunStateStringStartingProvider
	case RunStateCodeHandshaking:
		return RunStateStringHandshaking
	case RunStateCodeRunning:
		return RunStateStringRunning
	case RunStateCodeWaitingToolApproval:
		return RunStateStringWaitingToolApproval
	case RunStateCodeToolRunning:
		return RunStateStringToolRunning
	case RunStateCodeWaitingProvider:
		return RunStateStringWaitingProvider
	case RunStateCodeCompleting:
		return RunStateStringCompleting
	case RunStateCodeCompleted:
		return RunStateStringCompleted
	case RunStateCodeFailed:
		return RunStateStringFailed
	case RunStateCodeCancelled:
		return RunStateStringCancelled
	case RunStateCodeTimedOut:
		return RunStateStringTimedOut
	case RunStateCodeIdleStopped:
		return RunStateStringIdleStopped
	default:
		return RunStateString("")
	}
}

func (code RunStateCode) String() string {
	return string(code.StringValue())
}

func (code RunStateCode) RunState() RunState {
	return RunState(code.StringValue())
}

func (value RunState) Valid() bool {
	return value.Code().IsKnown()
}

func AllRunStateCodes() []RunStateCode {
	return []RunStateCode{
		RunStateCodePending,
		RunStateCodePreparing,
		RunStateCodeStartingProvider,
		RunStateCodeHandshaking,
		RunStateCodeRunning,
		RunStateCodeWaitingToolApproval,
		RunStateCodeToolRunning,
		RunStateCodeWaitingProvider,
		RunStateCodeCompleting,
		RunStateCodeCompleted,
		RunStateCodeFailed,
		RunStateCodeCancelled,
		RunStateCodeTimedOut,
		RunStateCodeIdleStopped,
	}
}

func AllStates() []RunState {
	codes := AllRunStateCodes()
	out := make([]RunState, len(codes))
	for index, code := range codes {
		out[index] = code.RunState()
	}
	return out
}

func (code RunStateCode) IsTerminal() bool {
	switch code {
	case RunStateCodeCompleted, RunStateCodeFailed, RunStateCodeCancelled, RunStateCodeTimedOut, RunStateCodeIdleStopped:
		return true
	default:
		return false
	}
}

func (value RunState) IsTerminal() bool {
	return value.Code().IsTerminal()
}
