// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package runstate

const (
	StatePending             RunState = RunState(RunStateStringPending)
	StatePreparing           RunState = RunState(RunStateStringPreparing)
	StateStartingProvider    RunState = RunState(RunStateStringStartingProvider)
	StateHandshaking         RunState = RunState(RunStateStringHandshaking)
	StateRunning             RunState = RunState(RunStateStringRunning)
	StateWaitingToolApproval RunState = RunState(RunStateStringWaitingToolApproval)
	StateToolRunning         RunState = RunState(RunStateStringToolRunning)
	StateWaitingProvider     RunState = RunState(RunStateStringWaitingProvider)
	StateCompleting          RunState = RunState(RunStateStringCompleting)
	StateCompleted           RunState = RunState(RunStateStringCompleted)
	StateFailed              RunState = RunState(RunStateStringFailed)
	StateCancelled           RunState = RunState(RunStateStringCancelled)
	StateTimedOut            RunState = RunState(RunStateStringTimedOut)
	StateIdleStopped         RunState = RunState(RunStateStringIdleStopped)
)
