// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package runstate

const (
	RunStateCodeUnknown RunStateCode = iota
	RunStateCodePending
	RunStateCodePreparing
	RunStateCodeStartingProvider
	RunStateCodeHandshaking
	RunStateCodeRunning
	RunStateCodeWaitingToolApproval
	RunStateCodeToolRunning
	RunStateCodeWaitingProvider
	RunStateCodeCompleting
	RunStateCodeCompleted
	RunStateCodeFailed
	RunStateCodeCancelled
	RunStateCodeTimedOut
	RunStateCodeIdleStopped
)
