// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package runstate

const (
	RunStateStringPending             RunStateString = "pending"
	RunStateStringPreparing           RunStateString = "preparing"
	RunStateStringStartingProvider    RunStateString = "starting_provider"
	RunStateStringHandshaking         RunStateString = "handshaking"
	RunStateStringRunning             RunStateString = "running"
	RunStateStringWaitingToolApproval RunStateString = "waiting_tool_approval"
	RunStateStringToolRunning         RunStateString = "tool_running"
	RunStateStringWaitingProvider     RunStateString = "waiting_provider"
	RunStateStringCompleting          RunStateString = "completing"
	RunStateStringCompleted           RunStateString = "completed"
	RunStateStringFailed              RunStateString = "failed"
	RunStateStringCancelled           RunStateString = "cancelled"
	RunStateStringTimedOut            RunStateString = "timed_out"
	RunStateStringIdleStopped         RunStateString = "idle_stopped"
)
