// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package runstate

func AllRunStateCodes() []RunStateCode {
	return append([]RunStateCode(nil), runStateAllCodes...)
}

func AllStates() []RunState {
	codes := AllRunStateCodes()
	out := make([]RunState, len(codes))
	for index, code := range codes {
		out[index] = code.RunState()
	}
	return out
}
