// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

const (
	ApprovalPending  ApprovalStatus = ApprovalStatus(ApprovalStatusStringPending)
	ApprovalApproved ApprovalStatus = ApprovalStatus(ApprovalStatusStringApproved)
	ApprovalDenied   ApprovalStatus = ApprovalStatus(ApprovalStatusStringDenied)
	ApprovalTimedOut ApprovalStatus = ApprovalStatus(ApprovalStatusStringTimedOut)
)
