// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

type ApprovalStatusCode uint16

type ApprovalStatusString string

const (
	ApprovalStatusCodeUnknown ApprovalStatusCode = iota
	ApprovalStatusCodePending
	ApprovalStatusCodeApproved
	ApprovalStatusCodeDenied
	ApprovalStatusCodeTimedOut
)

const (
	ApprovalStatusStringPending  ApprovalStatusString = "pending"
	ApprovalStatusStringApproved ApprovalStatusString = "approved"
	ApprovalStatusStringDenied   ApprovalStatusString = "denied"
	ApprovalStatusStringTimedOut ApprovalStatusString = "timed_out"
)

const (
	ApprovalPending  ApprovalStatus = ApprovalStatus(ApprovalStatusStringPending)
	ApprovalApproved ApprovalStatus = ApprovalStatus(ApprovalStatusStringApproved)
	ApprovalDenied   ApprovalStatus = ApprovalStatus(ApprovalStatusStringDenied)
	ApprovalTimedOut ApprovalStatus = ApprovalStatus(ApprovalStatusStringTimedOut)
)

func (value ApprovalStatus) Code() ApprovalStatusCode {
	return ParseApprovalStatusCode(string(value))
}

func ParseApprovalStatusCode(value string) ApprovalStatusCode {
	switch ApprovalStatusString(value) {
	case ApprovalStatusStringPending:
		return ApprovalStatusCodePending
	case ApprovalStatusStringApproved:
		return ApprovalStatusCodeApproved
	case ApprovalStatusStringDenied:
		return ApprovalStatusCodeDenied
	case ApprovalStatusStringTimedOut:
		return ApprovalStatusCodeTimedOut
	default:
		return ApprovalStatusCodeUnknown
	}
}

func (code ApprovalStatusCode) IsKnown() bool {
	return code >= ApprovalStatusCodePending && code <= ApprovalStatusCodeTimedOut
}

func (code ApprovalStatusCode) StringValue() ApprovalStatusString {
	switch code {
	case ApprovalStatusCodePending:
		return ApprovalStatusStringPending
	case ApprovalStatusCodeApproved:
		return ApprovalStatusStringApproved
	case ApprovalStatusCodeDenied:
		return ApprovalStatusStringDenied
	case ApprovalStatusCodeTimedOut:
		return ApprovalStatusStringTimedOut
	default:
		return ApprovalStatusString("")
	}
}

func (code ApprovalStatusCode) String() string {
	return string(code.StringValue())
}

func (code ApprovalStatusCode) ApprovalStatus() ApprovalStatus {
	return ApprovalStatus(code.StringValue())
}

func (value ApprovalStatus) Valid() bool {
	return value.Code().IsKnown()
}

func AllApprovalStatusCodes() []ApprovalStatusCode {
	return []ApprovalStatusCode{
		ApprovalStatusCodePending,
		ApprovalStatusCodeApproved,
		ApprovalStatusCodeDenied,
		ApprovalStatusCodeTimedOut,
	}
}

func AllApprovalStatuses() []ApprovalStatus {
	codes := AllApprovalStatusCodes()
	out := make([]ApprovalStatus, len(codes))
	for index, code := range codes {
		out[index] = code.ApprovalStatus()
	}
	return out
}
