// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

func AllApprovalStatusCodes() []ApprovalStatusCode {
	return append([]ApprovalStatusCode(nil), approvalStatusAllCodes...)
}

func AllApprovalStatuses() []ApprovalStatus {
	codes := AllApprovalStatusCodes()
	out := make([]ApprovalStatus, len(codes))
	for index, code := range codes {
		out[index] = code.ApprovalStatus()
	}
	return out
}
