// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

var approvalStatusStringByCode = map[ApprovalStatusCode]ApprovalStatusString{
	ApprovalStatusCodePending:  ApprovalStatusStringPending,
	ApprovalStatusCodeApproved: ApprovalStatusStringApproved,
	ApprovalStatusCodeDenied:   ApprovalStatusStringDenied,
	ApprovalStatusCodeTimedOut: ApprovalStatusStringTimedOut,
}
