// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

const (
	ApprovalDecisionCodeUnknown ApprovalDecisionCode = iota
	ApprovalDecisionCodeApprove
	ApprovalDecisionCodeDeny
)
