// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

func AllApprovalDecisionCodes() []ApprovalDecisionCode {
	return append([]ApprovalDecisionCode(nil), approvalDecisionAllCodes...)
}

func AllApprovalDecisions() []ApprovalDecision {
	codes := AllApprovalDecisionCodes()
	out := make([]ApprovalDecision, len(codes))
	for index, code := range codes {
		out[index] = code.ApprovalDecision()
	}
	return out
}
