// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

const (
	ApprovalStatusCodeUnknown ApprovalStatusCode = iota
	ApprovalStatusCodePending
	ApprovalStatusCodeApproved
	ApprovalStatusCodeDenied
	ApprovalStatusCodeTimedOut
)
