// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

func (value ApprovalStatus) Code() ApprovalStatusCode {
	return ParseApprovalStatusCode(string(value))
}

func ParseApprovalStatusCode(value string) ApprovalStatusCode {
	code, ok := approvalStatusCodeByString[ApprovalStatusString(value)]
	if !ok {
		return ApprovalStatusCodeUnknown
	}
	return code
}
