// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

type ApprovalDecisionCode uint16

type ApprovalDecisionString string

const (
	ApprovalDecisionCodeUnknown ApprovalDecisionCode = iota
	ApprovalDecisionCodeApprove
	ApprovalDecisionCodeDeny
)

const (
	ApprovalDecisionStringApprove ApprovalDecisionString = "approve"
	ApprovalDecisionStringDeny    ApprovalDecisionString = "deny"
)

const (
	ApprovalDecisionApprove ApprovalDecision = ApprovalDecision(ApprovalDecisionStringApprove)
	ApprovalDecisionDeny    ApprovalDecision = ApprovalDecision(ApprovalDecisionStringDeny)
)

func (value ApprovalDecision) Code() ApprovalDecisionCode {
	return ParseApprovalDecisionCode(string(value))
}

func ParseApprovalDecisionCode(value string) ApprovalDecisionCode {
	switch ApprovalDecisionString(value) {
	case ApprovalDecisionStringApprove:
		return ApprovalDecisionCodeApprove
	case ApprovalDecisionStringDeny:
		return ApprovalDecisionCodeDeny
	default:
		return ApprovalDecisionCodeUnknown
	}
}

func (code ApprovalDecisionCode) IsKnown() bool {
	return code >= ApprovalDecisionCodeApprove && code <= ApprovalDecisionCodeDeny
}

func (code ApprovalDecisionCode) StringValue() ApprovalDecisionString {
	switch code {
	case ApprovalDecisionCodeApprove:
		return ApprovalDecisionStringApprove
	case ApprovalDecisionCodeDeny:
		return ApprovalDecisionStringDeny
	default:
		return ApprovalDecisionString("")
	}
}

func (code ApprovalDecisionCode) String() string {
	return string(code.StringValue())
}

func (code ApprovalDecisionCode) ApprovalDecision() ApprovalDecision {
	return ApprovalDecision(code.StringValue())
}

func (value ApprovalDecision) Valid() bool {
	return value.Code().IsKnown()
}

func AllApprovalDecisionCodes() []ApprovalDecisionCode {
	return []ApprovalDecisionCode{
		ApprovalDecisionCodeApprove,
		ApprovalDecisionCodeDeny,
	}
}

func AllApprovalDecisions() []ApprovalDecision {
	codes := AllApprovalDecisionCodes()
	out := make([]ApprovalDecision, len(codes))
	for index, code := range codes {
		out[index] = code.ApprovalDecision()
	}
	return out
}
