// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

var approvalDecisionStringByCode = map[ApprovalDecisionCode]ApprovalDecisionString{
	ApprovalDecisionCodeApprove: ApprovalDecisionStringApprove,
	ApprovalDecisionCodeDeny:    ApprovalDecisionStringDeny,
}
