// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

func (code ApprovalStatusCode) IsKnown() bool {
	_, ok := approvalStatusStringByCode[code]
	return ok
}

func (code ApprovalStatusCode) StringValue() ApprovalStatusString {
	return approvalStatusStringByCode[code]
}

func (code ApprovalStatusCode) String() string {
	return string(code.StringValue())
}

func (code ApprovalStatusCode) ApprovalStatus() ApprovalStatus {
	return ApprovalStatus(code.StringValue())
}
