// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

const (
	ApprovalDecisionStringApprove ApprovalDecisionString = "approve"
	ApprovalDecisionStringDeny    ApprovalDecisionString = "deny"
)
