// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

var approvalStatusAllCodes = []ApprovalStatusCode{
	ApprovalStatusCodePending,
	ApprovalStatusCodeApproved,
	ApprovalStatusCodeDenied,
	ApprovalStatusCodeTimedOut,
}
