// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

var approvalStatusCodeByString = map[ApprovalStatusString]ApprovalStatusCode{
	ApprovalStatusStringPending:  ApprovalStatusCodePending,
	ApprovalStatusStringApproved: ApprovalStatusCodeApproved,
	ApprovalStatusStringDenied:   ApprovalStatusCodeDenied,
	ApprovalStatusStringTimedOut: ApprovalStatusCodeTimedOut,
}
