// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

func (code ApprovalDecisionCode) IsKnown() bool {
	_, ok := approvalDecisionStringByCode[code]
	return ok
}

func (code ApprovalDecisionCode) StringValue() ApprovalDecisionString {
	return approvalDecisionStringByCode[code]
}

func (code ApprovalDecisionCode) String() string {
	return string(code.StringValue())
}

func (code ApprovalDecisionCode) ApprovalDecision() ApprovalDecision {
	return ApprovalDecision(code.StringValue())
}
