// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

var approvalDecisionCodeByString = map[ApprovalDecisionString]ApprovalDecisionCode{
	ApprovalDecisionStringApprove: ApprovalDecisionCodeApprove,
	ApprovalDecisionStringDeny:    ApprovalDecisionCodeDeny,
}
