// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

const (
	ApprovalStatusStringPending  ApprovalStatusString = "pending"
	ApprovalStatusStringApproved ApprovalStatusString = "approved"
	ApprovalStatusStringDenied   ApprovalStatusString = "denied"
	ApprovalStatusStringTimedOut ApprovalStatusString = "timed_out"
)
