// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

func (value ApprovalDecision) Code() ApprovalDecisionCode {
	return ParseApprovalDecisionCode(string(value))
}

func ParseApprovalDecisionCode(value string) ApprovalDecisionCode {
	code, ok := approvalDecisionCodeByString[ApprovalDecisionString(value)]
	if !ok {
		return ApprovalDecisionCodeUnknown
	}
	return code
}
