// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

type AssignmentTransitionCode struct {
	From AssignmentStateCode
	To   AssignmentStateCode
}

func AssignmentTransitionCodes() []AssignmentTransitionCode {
	return []AssignmentTransitionCode{
		{From: AssignmentStateCodeQueued, To: AssignmentStateCodeLeased},
		{From: AssignmentStateCodeQueued, To: AssignmentStateCodeCancelling},
		{From: AssignmentStateCodeQueued, To: AssignmentStateCodeCancelled},
		{From: AssignmentStateCodeQueued, To: AssignmentStateCodeFailed},
		{From: AssignmentStateCodeLeased, To: AssignmentStateCodeReady},
		{From: AssignmentStateCodeLeased, To: AssignmentStateCodeRunning},
		{From: AssignmentStateCodeLeased, To: AssignmentStateCodeCancelling},
		{From: AssignmentStateCodeLeased, To: AssignmentStateCodeCancelled},
		{From: AssignmentStateCodeLeased, To: AssignmentStateCodeFailed},
		{From: AssignmentStateCodeReady, To: AssignmentStateCodeRunning},
		{From: AssignmentStateCodeReady, To: AssignmentStateCodeCancelling},
		{From: AssignmentStateCodeReady, To: AssignmentStateCodeCancelled},
		{From: AssignmentStateCodeReady, To: AssignmentStateCodeFailed},
		{From: AssignmentStateCodeRunning, To: AssignmentStateCodeCompleted},
		{From: AssignmentStateCodeRunning, To: AssignmentStateCodeFailed},
		{From: AssignmentStateCodeRunning, To: AssignmentStateCodeCancelling},
		{From: AssignmentStateCodeRunning, To: AssignmentStateCodeCancelled},
		{From: AssignmentStateCodeCancelling, To: AssignmentStateCodeCancelled},
		{From: AssignmentStateCodeCancelling, To: AssignmentStateCodeFailed},
	}
}

func CanTransitionCode(from AssignmentStateCode, to AssignmentStateCode) bool {
	if from == to && from.IsKnown() {
		return true
	}
	switch from {
	case AssignmentStateCodeQueued:
		switch to {
		case AssignmentStateCodeLeased:
			return true
		case AssignmentStateCodeCancelling:
			return true
		case AssignmentStateCodeCancelled:
			return true
		case AssignmentStateCodeFailed:
			return true
		}
	case AssignmentStateCodeLeased:
		switch to {
		case AssignmentStateCodeReady:
			return true
		case AssignmentStateCodeRunning:
			return true
		case AssignmentStateCodeCancelling:
			return true
		case AssignmentStateCodeCancelled:
			return true
		case AssignmentStateCodeFailed:
			return true
		}
	case AssignmentStateCodeReady:
		switch to {
		case AssignmentStateCodeRunning:
			return true
		case AssignmentStateCodeCancelling:
			return true
		case AssignmentStateCodeCancelled:
			return true
		case AssignmentStateCodeFailed:
			return true
		}
	case AssignmentStateCodeRunning:
		switch to {
		case AssignmentStateCodeCancelling:
			return true
		case AssignmentStateCodeCancelled:
			return true
		case AssignmentStateCodeCompleted:
			return true
		case AssignmentStateCodeFailed:
			return true
		}
	case AssignmentStateCodeCancelling:
		switch to {
		case AssignmentStateCodeCancelled:
			return true
		case AssignmentStateCodeFailed:
			return true
		}
	}
	return false
}
