// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

func (code AssignmentStateCode) IsTerminal() bool {
	switch code {
	case AssignmentStateCodeCancelled, AssignmentStateCodeCompleted, AssignmentStateCodeFailed:
		return true
	default:
		return false
	}
}

func (value AssignmentState) IsTerminal() bool {
	return value.Code().IsTerminal()
}

func (code AssignmentStateCode) IsAgentActive() bool {
	switch code {
	case AssignmentStateCodeLeased, AssignmentStateCodeReady, AssignmentStateCodeRunning:
		return true
	default:
		return false
	}
}

func (value AssignmentState) IsAgentActive() bool {
	return value.Code().IsAgentActive()
}

func IsTerminal(value AssignmentState) bool {
	return value.Code().IsTerminal()
}

func IsAgentActive(value AssignmentState) bool {
	return value.Code().IsAgentActive()
}
