// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

func AllAssignmentStateCodes() []AssignmentStateCode {
	return append([]AssignmentStateCode(nil), assignmentStateAllCodes...)
}

func AllAssignmentStates() []AssignmentState {
	codes := AllAssignmentStateCodes()
	out := make([]AssignmentState, len(codes))
	for index, code := range codes {
		out[index] = code.AssignmentState()
	}
	return out
}
