// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

func CanTransitionCode(from AssignmentStateCode, to AssignmentStateCode) bool {
	if from == to && from.IsKnown() {
		return true
	}
	return assignmentTransitionCodeAllowed[AssignmentTransitionCode{From: from, To: to}]
}
