// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

const (
	AssignmentQueued     AssignmentState = AssignmentState(AssignmentStateStringQueued)
	AssignmentLeased     AssignmentState = AssignmentState(AssignmentStateStringLeased)
	AssignmentReady      AssignmentState = AssignmentState(AssignmentStateStringReady)
	AssignmentRunning    AssignmentState = AssignmentState(AssignmentStateStringRunning)
	AssignmentCancelling AssignmentState = AssignmentState(AssignmentStateStringCancelling)
	AssignmentCancelled  AssignmentState = AssignmentState(AssignmentStateStringCancelled)
	AssignmentCompleted  AssignmentState = AssignmentState(AssignmentStateStringCompleted)
	AssignmentFailed     AssignmentState = AssignmentState(AssignmentStateStringFailed)
)
