// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

func (value AssignmentState) Code() AssignmentStateCode {
	return ParseAssignmentStateCode(string(value))
}

func ParseAssignmentStateCode(value string) AssignmentStateCode {
	code, ok := assignmentStateCodeByString[AssignmentStateString(value)]
	if !ok {
		return AssignmentStateCodeUnknown
	}
	return code
}
