// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

const (
	AssignmentStateCodeUnknown AssignmentStateCode = iota
	AssignmentStateCodeQueued
	AssignmentStateCodeLeased
	AssignmentStateCodeReady
	AssignmentStateCodeRunning
	AssignmentStateCodeCancelling
	AssignmentStateCodeCancelled
	AssignmentStateCodeCompleted
	AssignmentStateCodeFailed
)
