// Code generated by fsm gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

func GeneratedAssignmentFSM() AssignmentFSM {
	return generatedAssignmentFSM{}
}

func GeneratedAssignmentFSMServiceProvider() AssignmentFSMServiceProvider {
	return generatedAssignmentFSMServiceProvider{}
}

func (generatedAssignmentFSMServiceProvider) AssignmentFSM() AssignmentFSM {
	return generatedAssignmentFSM{}
}

func (generatedAssignmentFSM) Name() string {
	return "assignment"
}

func (generatedAssignmentFSM) TypeUnion() AssignmentFSMTypeUnion {
	return AssignmentFSMTypeUnionAssignmentPollingFSM
}
