// Code generated by fsm gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

var assignmentFSMNextStates = map[AssignmentStateCode][]AssignmentStateCode{
	AssignmentStateCodeQueued:     []AssignmentStateCode{AssignmentStateCodeQueued, AssignmentStateCodeLeased, AssignmentStateCodeCancelling, AssignmentStateCodeCancelled, AssignmentStateCodeFailed},
	AssignmentStateCodeLeased:     []AssignmentStateCode{AssignmentStateCodeLeased, AssignmentStateCodeReady, AssignmentStateCodeRunning, AssignmentStateCodeCancelling, AssignmentStateCodeCancelled, AssignmentStateCodeFailed},
	AssignmentStateCodeReady:      []AssignmentStateCode{AssignmentStateCodeReady, AssignmentStateCodeRunning, AssignmentStateCodeCancelling, AssignmentStateCodeCancelled, AssignmentStateCodeFailed},
	AssignmentStateCodeRunning:    []AssignmentStateCode{AssignmentStateCodeRunning, AssignmentStateCodeCancelling, AssignmentStateCodeCancelled, AssignmentStateCodeCompleted, AssignmentStateCodeFailed},
	AssignmentStateCodeCancelling: []AssignmentStateCode{AssignmentStateCodeCancelling, AssignmentStateCodeCancelled, AssignmentStateCodeFailed},
	AssignmentStateCodeCancelled:  []AssignmentStateCode{AssignmentStateCodeCancelled},
	AssignmentStateCodeCompleted:  []AssignmentStateCode{AssignmentStateCodeCompleted},
	AssignmentStateCodeFailed:     []AssignmentStateCode{AssignmentStateCodeFailed},
}
