// Code generated by fsm gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

var assignmentFSMStartStates = []AssignmentStateCode{
	AssignmentStateCodeQueued,
}

var assignmentFSMEndStates = []AssignmentStateCode{
	AssignmentStateCodeCancelled,
	AssignmentStateCodeCompleted,
	AssignmentStateCodeFailed,
}

func (generatedAssignmentFSM) States() []AssignmentStateCode {
	return AllAssignmentStateCodes()
}

func (generatedAssignmentFSM) StartStates() []AssignmentStateCode {
	return append([]AssignmentStateCode(nil), assignmentFSMStartStates...)
}

func (generatedAssignmentFSM) EndStates() []AssignmentStateCode {
	return append([]AssignmentStateCode(nil), assignmentFSMEndStates...)
}

func (generatedAssignmentFSM) TerminalStates() []AssignmentStateCode {
	return append([]AssignmentStateCode(nil), assignmentFSMEndStates...)
}

func (generatedAssignmentFSM) Transitions() []AssignmentTransitionCode {
	return AssignmentTransitionCodes()
}
