// Code generated by fsm gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

var assignmentFSMStartStateSet = map[AssignmentStateCode]bool{
	AssignmentStateCodeQueued: true,
}

var assignmentFSMEndStateSet = map[AssignmentStateCode]bool{
	AssignmentStateCodeCancelled: true,
	AssignmentStateCodeCompleted: true,
	AssignmentStateCodeFailed:    true,
}

func (fsm generatedAssignmentFSM) PointKind(state AssignmentStateCode) AssignmentFSMPointKind {
	switch {
	case fsm.IsStartState(state):
		return AssignmentFSMPointStart
	case fsm.IsEndState(state):
		return AssignmentFSMPointEnd
	case state.IsKnown():
		return AssignmentFSMPointIntermediate
	default:
		return AssignmentFSMPointUnknown
	}
}

func (generatedAssignmentFSM) IsStartState(state AssignmentStateCode) bool {
	return assignmentFSMStartStateSet[state]
}

func (generatedAssignmentFSM) IsEndState(state AssignmentStateCode) bool {
	return assignmentFSMEndStateSet[state]
}
