// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

func (code AssignmentStateCode) IsKnown() bool {
	_, ok := assignmentStateStringByCode[code]
	return ok
}

func (code AssignmentStateCode) StringValue() AssignmentStateString {
	return assignmentStateStringByCode[code]
}

func (code AssignmentStateCode) String() string {
	return string(code.StringValue())
}

func (code AssignmentStateCode) AssignmentState() AssignmentState {
	return AssignmentState(code.StringValue())
}
