// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

var assignmentStateAllCodes = []AssignmentStateCode{
	AssignmentStateCodeQueued,
	AssignmentStateCodeLeased,
	AssignmentStateCodeReady,
	AssignmentStateCodeRunning,
	AssignmentStateCodeCancelling,
	AssignmentStateCodeCancelled,
	AssignmentStateCodeCompleted,
	AssignmentStateCodeFailed,
}
