// Code generated by fsm gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

func (generatedAssignmentFSM) CanTransition(from AssignmentStateCode, to AssignmentStateCode) bool {
	return CanTransitionCode(from, to)
}

func (generatedAssignmentFSM) NextStates(from AssignmentStateCode) []AssignmentStateCode {
	states := assignmentFSMNextStates[from]
	return append([]AssignmentStateCode(nil), states...)
}
