// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

var assignmentStateStringByCode = map[AssignmentStateCode]AssignmentStateString{
	AssignmentStateCodeQueued:     AssignmentStateStringQueued,
	AssignmentStateCodeLeased:     AssignmentStateStringLeased,
	AssignmentStateCodeReady:      AssignmentStateStringReady,
	AssignmentStateCodeRunning:    AssignmentStateStringRunning,
	AssignmentStateCodeCancelling: AssignmentStateStringCancelling,
	AssignmentStateCodeCancelled:  AssignmentStateStringCancelled,
	AssignmentStateCodeCompleted:  AssignmentStateStringCompleted,
	AssignmentStateCodeFailed:     AssignmentStateStringFailed,
}
