// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

const (
	AssignmentStateStringQueued     AssignmentStateString = "queued"
	AssignmentStateStringLeased     AssignmentStateString = "leased"
	AssignmentStateStringReady      AssignmentStateString = "ready"
	AssignmentStateStringRunning    AssignmentStateString = "running"
	AssignmentStateStringCancelling AssignmentStateString = "cancelling"
	AssignmentStateStringCancelled  AssignmentStateString = "cancelled"
	AssignmentStateStringCompleted  AssignmentStateString = "completed"
	AssignmentStateStringFailed     AssignmentStateString = "failed"
)
