// Code generated by fsm gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

type AssignmentFSMTypeUnion string

const (
	AssignmentFSMTypeUnionAssignmentPollingFSM AssignmentFSMTypeUnion = "AssignmentPollingFSM"
)

type AssignmentFSMPointKind uint8

const (
	AssignmentFSMPointUnknown AssignmentFSMPointKind = iota
	AssignmentFSMPointStart
	AssignmentFSMPointIntermediate
	AssignmentFSMPointEnd
)

type AssignmentFSM interface {
	Name() string
	TypeUnion() AssignmentFSMTypeUnion
	States() []AssignmentStateCode
	StartStates() []AssignmentStateCode
	EndStates() []AssignmentStateCode
	TerminalStates() []AssignmentStateCode
	Transitions() []AssignmentTransitionCode
	PointKind(state AssignmentStateCode) AssignmentFSMPointKind
	IsStartState(state AssignmentStateCode) bool
	IsEndState(state AssignmentStateCode) bool
	CanTransition(from AssignmentStateCode, to AssignmentStateCode) bool
	NextStates(from AssignmentStateCode) []AssignmentStateCode
	Mermaid() string
}

type AssignmentFSMServiceProvider interface {
	AssignmentFSM() AssignmentFSM
}

type generatedAssignmentFSM struct{}

type generatedAssignmentFSMServiceProvider struct{}

func GeneratedAssignmentFSM() AssignmentFSM {
	return generatedAssignmentFSM{}
}

func GeneratedAssignmentFSMServiceProvider() AssignmentFSMServiceProvider {
	return generatedAssignmentFSMServiceProvider{}
}

func (generatedAssignmentFSMServiceProvider) AssignmentFSM() AssignmentFSM {
	return generatedAssignmentFSM{}
}

func (generatedAssignmentFSM) Name() string {
	return "assignment"
}

func (generatedAssignmentFSM) TypeUnion() AssignmentFSMTypeUnion {
	return AssignmentFSMTypeUnionAssignmentPollingFSM
}

func (generatedAssignmentFSM) States() []AssignmentStateCode {
	return AllAssignmentStateCodes()
}

func (generatedAssignmentFSM) StartStates() []AssignmentStateCode {
	return []AssignmentStateCode{
		AssignmentStateCodeQueued,
	}
}

func (generatedAssignmentFSM) EndStates() []AssignmentStateCode {
	return []AssignmentStateCode{
		AssignmentStateCodeCancelled,
		AssignmentStateCodeCompleted,
		AssignmentStateCodeFailed,
	}
}

func (generatedAssignmentFSM) TerminalStates() []AssignmentStateCode {
	return []AssignmentStateCode{
		AssignmentStateCodeCancelled,
		AssignmentStateCodeCompleted,
		AssignmentStateCodeFailed,
	}
}

func (generatedAssignmentFSM) Transitions() []AssignmentTransitionCode {
	return AssignmentTransitionCodes()
}

func (fsm generatedAssignmentFSM) PointKind(state AssignmentStateCode) AssignmentFSMPointKind {
	switch {
	case fsm.IsStartState(state):
		return AssignmentFSMPointStart
	case fsm.IsEndState(state):
		return AssignmentFSMPointEnd
	case state.IsKnown():
		return AssignmentFSMPointIntermediate
	default:
		return AssignmentFSMPointUnknown
	}
}

func (generatedAssignmentFSM) IsStartState(state AssignmentStateCode) bool {
	switch state {
	case AssignmentStateCodeQueued:
		return true
	default:
		return false
	}
}

func (generatedAssignmentFSM) IsEndState(state AssignmentStateCode) bool {
	switch state {
	case AssignmentStateCodeCancelled:
		return true
	case AssignmentStateCodeCompleted:
		return true
	case AssignmentStateCodeFailed:
		return true
	default:
		return false
	}
}

func (generatedAssignmentFSM) CanTransition(from AssignmentStateCode, to AssignmentStateCode) bool {
	return CanTransitionCode(from, to)
}

func (generatedAssignmentFSM) NextStates(from AssignmentStateCode) []AssignmentStateCode {
	switch from {
	case AssignmentStateCodeQueued:
		return []AssignmentStateCode{
			AssignmentStateCodeQueued,
			AssignmentStateCodeLeased,
			AssignmentStateCodeCancelling,
			AssignmentStateCodeCancelled,
			AssignmentStateCodeFailed,
		}
	case AssignmentStateCodeLeased:
		return []AssignmentStateCode{
			AssignmentStateCodeLeased,
			AssignmentStateCodeReady,
			AssignmentStateCodeRunning,
			AssignmentStateCodeCancelling,
			AssignmentStateCodeCancelled,
			AssignmentStateCodeFailed,
		}
	case AssignmentStateCodeReady:
		return []AssignmentStateCode{
			AssignmentStateCodeReady,
			AssignmentStateCodeRunning,
			AssignmentStateCodeCancelling,
			AssignmentStateCodeCancelled,
			AssignmentStateCodeFailed,
		}
	case AssignmentStateCodeRunning:
		return []AssignmentStateCode{
			AssignmentStateCodeRunning,
			AssignmentStateCodeCancelling,
			AssignmentStateCodeCancelled,
			AssignmentStateCodeCompleted,
			AssignmentStateCodeFailed,
		}
	case AssignmentStateCodeCancelling:
		return []AssignmentStateCode{
			AssignmentStateCodeCancelling,
			AssignmentStateCodeCancelled,
			AssignmentStateCodeFailed,
		}
	case AssignmentStateCodeCancelled:
		return []AssignmentStateCode{
			AssignmentStateCodeCancelled,
		}
	case AssignmentStateCodeCompleted:
		return []AssignmentStateCode{
			AssignmentStateCodeCompleted,
		}
	case AssignmentStateCodeFailed:
		return []AssignmentStateCode{
			AssignmentStateCodeFailed,
		}
	}
	return nil
}

const AssignmentFSMMermaid = `stateDiagram-v2
  [*] --> Queued
  Queued --> Leased
  Queued --> Cancelling
  Queued --> Cancelled
  Queued --> Failed
  Leased --> Ready
  Leased --> Running
  Leased --> Cancelling
  Leased --> Cancelled
  Leased --> Failed
  Ready --> Running
  Ready --> Cancelling
  Ready --> Cancelled
  Ready --> Failed
  Running --> Completed
  Running --> Failed
  Running --> Cancelling
  Running --> Cancelled
  Cancelling --> Cancelled
  Cancelling --> Failed
  Cancelled --> [*]
  Completed --> [*]
  Failed --> [*]
`

func (generatedAssignmentFSM) Mermaid() string {
	return AssignmentFSMMermaid
}
