// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

var assignmentTransitionCodeAll = []AssignmentTransitionCode{
	{From: AssignmentStateCodeQueued, To: AssignmentStateCodeLeased},
	{From: AssignmentStateCodeQueued, To: AssignmentStateCodeCancelling},
	{From: AssignmentStateCodeQueued, To: AssignmentStateCodeCancelled},
	{From: AssignmentStateCodeQueued, To: AssignmentStateCodeFailed},
	{From: AssignmentStateCodeLeased, To: AssignmentStateCodeReady},
	{From: AssignmentStateCodeLeased, To: AssignmentStateCodeRunning},
	{From: AssignmentStateCodeLeased, To: AssignmentStateCodeCancelling},
	{From: AssignmentStateCodeLeased, To: AssignmentStateCodeCancelled},
	{From: AssignmentStateCodeLeased, To: AssignmentStateCodeFailed},
	{From: AssignmentStateCodeReady, To: AssignmentStateCodeRunning},
	{From: AssignmentStateCodeReady, To: AssignmentStateCodeCancelling},
	{From: AssignmentStateCodeReady, To: AssignmentStateCodeCancelled},
	{From: AssignmentStateCodeReady, To: AssignmentStateCodeFailed},
	{From: AssignmentStateCodeRunning, To: AssignmentStateCodeCompleted},
	{From: AssignmentStateCodeRunning, To: AssignmentStateCodeFailed},
	{From: AssignmentStateCodeRunning, To: AssignmentStateCodeCancelling},
	{From: AssignmentStateCodeRunning, To: AssignmentStateCodeCancelled},
	{From: AssignmentStateCodeCancelling, To: AssignmentStateCodeCancelled},
	{From: AssignmentStateCodeCancelling, To: AssignmentStateCodeFailed},
}

func AssignmentTransitionCodes() []AssignmentTransitionCode {
	return append([]AssignmentTransitionCode(nil), assignmentTransitionCodeAll...)
}
