// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

type AssignmentStateCode uint16

type AssignmentStateString string

const (
	AssignmentStateCodeUnknown AssignmentStateCode = iota
	AssignmentStateCodeQueued
	AssignmentStateCodeLeased
	AssignmentStateCodeReady
	AssignmentStateCodeRunning
	AssignmentStateCodeCancelling
	AssignmentStateCodeCancelled
	AssignmentStateCodeCompleted
	AssignmentStateCodeFailed
)

const (
	AssignmentStateStringQueued     AssignmentStateString = "queued"
	AssignmentStateStringLeased     AssignmentStateString = "leased"
	AssignmentStateStringReady      AssignmentStateString = "ready"
	AssignmentStateStringRunning    AssignmentStateString = "running"
	AssignmentStateStringCancelling AssignmentStateString = "cancelling"
	AssignmentStateStringCancelled  AssignmentStateString = "cancelled"
	AssignmentStateStringCompleted  AssignmentStateString = "completed"
	AssignmentStateStringFailed     AssignmentStateString = "failed"
)

const (
	AssignmentQueued     AssignmentState = AssignmentState(AssignmentStateStringQueued)
	AssignmentLeased     AssignmentState = AssignmentState(AssignmentStateStringLeased)
	AssignmentReady      AssignmentState = AssignmentState(AssignmentStateStringReady)
	AssignmentRunning    AssignmentState = AssignmentState(AssignmentStateStringRunning)
	AssignmentCancelling AssignmentState = AssignmentState(AssignmentStateStringCancelling)
	AssignmentCancelled  AssignmentState = AssignmentState(AssignmentStateStringCancelled)
	AssignmentCompleted  AssignmentState = AssignmentState(AssignmentStateStringCompleted)
	AssignmentFailed     AssignmentState = AssignmentState(AssignmentStateStringFailed)
)

func (value AssignmentState) Code() AssignmentStateCode {
	return ParseAssignmentStateCode(string(value))
}

func ParseAssignmentStateCode(value string) AssignmentStateCode {
	switch AssignmentStateString(value) {
	case AssignmentStateStringQueued:
		return AssignmentStateCodeQueued
	case AssignmentStateStringLeased:
		return AssignmentStateCodeLeased
	case AssignmentStateStringReady:
		return AssignmentStateCodeReady
	case AssignmentStateStringRunning:
		return AssignmentStateCodeRunning
	case AssignmentStateStringCancelling:
		return AssignmentStateCodeCancelling
	case AssignmentStateStringCancelled:
		return AssignmentStateCodeCancelled
	case AssignmentStateStringCompleted:
		return AssignmentStateCodeCompleted
	case AssignmentStateStringFailed:
		return AssignmentStateCodeFailed
	default:
		return AssignmentStateCodeUnknown
	}
}

func (code AssignmentStateCode) IsKnown() bool {
	return code >= AssignmentStateCodeQueued && code <= AssignmentStateCodeFailed
}

func (code AssignmentStateCode) StringValue() AssignmentStateString {
	switch code {
	case AssignmentStateCodeQueued:
		return AssignmentStateStringQueued
	case AssignmentStateCodeLeased:
		return AssignmentStateStringLeased
	case AssignmentStateCodeReady:
		return AssignmentStateStringReady
	case AssignmentStateCodeRunning:
		return AssignmentStateStringRunning
	case AssignmentStateCodeCancelling:
		return AssignmentStateStringCancelling
	case AssignmentStateCodeCancelled:
		return AssignmentStateStringCancelled
	case AssignmentStateCodeCompleted:
		return AssignmentStateStringCompleted
	case AssignmentStateCodeFailed:
		return AssignmentStateStringFailed
	default:
		return AssignmentStateString("")
	}
}

func (code AssignmentStateCode) String() string {
	return string(code.StringValue())
}

func (code AssignmentStateCode) AssignmentState() AssignmentState {
	return AssignmentState(code.StringValue())
}

func (value AssignmentState) Valid() bool {
	return value.Code().IsKnown()
}

func AllAssignmentStateCodes() []AssignmentStateCode {
	return []AssignmentStateCode{
		AssignmentStateCodeQueued,
		AssignmentStateCodeLeased,
		AssignmentStateCodeReady,
		AssignmentStateCodeRunning,
		AssignmentStateCodeCancelling,
		AssignmentStateCodeCancelled,
		AssignmentStateCodeCompleted,
		AssignmentStateCodeFailed,
	}
}

func AllAssignmentStates() []AssignmentState {
	codes := AllAssignmentStateCodes()
	out := make([]AssignmentState, len(codes))
	for index, code := range codes {
		out[index] = code.AssignmentState()
	}
	return out
}

func (code AssignmentStateCode) IsTerminal() bool {
	switch code {
	case AssignmentStateCodeCancelled, AssignmentStateCodeCompleted, AssignmentStateCodeFailed:
		return true
	default:
		return false
	}
}

func (value AssignmentState) IsTerminal() bool {
	return value.Code().IsTerminal()
}

func (code AssignmentStateCode) IsAgentActive() bool {
	switch code {
	case AssignmentStateCodeLeased, AssignmentStateCodeReady, AssignmentStateCodeRunning:
		return true
	default:
		return false
	}
}

func (value AssignmentState) IsAgentActive() bool {
	return value.Code().IsAgentActive()
}

func IsTerminal(value AssignmentState) bool {
	return value.Code().IsTerminal()
}

func IsAgentActive(value AssignmentState) bool {
	return value.Code().IsAgentActive()
}
