// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

var assignmentTransitionCodeAllowed = map[AssignmentTransitionCode]bool{
	{From: AssignmentStateCodeQueued, To: AssignmentStateCodeLeased}:        true,
	{From: AssignmentStateCodeQueued, To: AssignmentStateCodeCancelling}:    true,
	{From: AssignmentStateCodeQueued, To: AssignmentStateCodeCancelled}:     true,
	{From: AssignmentStateCodeQueued, To: AssignmentStateCodeFailed}:        true,
	{From: AssignmentStateCodeLeased, To: AssignmentStateCodeReady}:         true,
	{From: AssignmentStateCodeLeased, To: AssignmentStateCodeRunning}:       true,
	{From: AssignmentStateCodeLeased, To: AssignmentStateCodeCancelling}:    true,
	{From: AssignmentStateCodeLeased, To: AssignmentStateCodeCancelled}:     true,
	{From: AssignmentStateCodeLeased, To: AssignmentStateCodeFailed}:        true,
	{From: AssignmentStateCodeReady, To: AssignmentStateCodeRunning}:        true,
	{From: AssignmentStateCodeReady, To: AssignmentStateCodeCancelling}:     true,
	{From: AssignmentStateCodeReady, To: AssignmentStateCodeCancelled}:      true,
	{From: AssignmentStateCodeReady, To: AssignmentStateCodeFailed}:         true,
	{From: AssignmentStateCodeRunning, To: AssignmentStateCodeCompleted}:    true,
	{From: AssignmentStateCodeRunning, To: AssignmentStateCodeFailed}:       true,
	{From: AssignmentStateCodeRunning, To: AssignmentStateCodeCancelling}:   true,
	{From: AssignmentStateCodeRunning, To: AssignmentStateCodeCancelled}:    true,
	{From: AssignmentStateCodeCancelling, To: AssignmentStateCodeCancelled}: true,
	{From: AssignmentStateCodeCancelling, To: AssignmentStateCodeFailed}:    true,
}
