// Code generated by fsm gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

type AssignmentFSMTypeUnion string

const (
	AssignmentFSMTypeUnionAssignmentPollingFSM AssignmentFSMTypeUnion = "AssignmentPollingFSM"
)

type AssignmentFSMPointKind uint8

const (
	AssignmentFSMPointUnknown AssignmentFSMPointKind = iota
	AssignmentFSMPointStart
	AssignmentFSMPointIntermediate
	AssignmentFSMPointEnd
)

type AssignmentFSM interface {
	Name() string
	TypeUnion() AssignmentFSMTypeUnion
	States() []AssignmentStateCode
	StartStates() []AssignmentStateCode
	EndStates() []AssignmentStateCode
	TerminalStates() []AssignmentStateCode
	Transitions() []AssignmentTransitionCode
	PointKind(state AssignmentStateCode) AssignmentFSMPointKind
	IsStartState(state AssignmentStateCode) bool
	IsEndState(state AssignmentStateCode) bool
	CanTransition(from AssignmentStateCode, to AssignmentStateCode) bool
	NextStates(from AssignmentStateCode) []AssignmentStateCode
	Mermaid() string
}

type AssignmentFSMServiceProvider interface {
	AssignmentFSM() AssignmentFSM
}

type generatedAssignmentFSM struct{}

type generatedAssignmentFSMServiceProvider struct{}
