// Code generated by fsm gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

type AssignmentFSM interface {
	Name() string
	States() []AssignmentStateCode
	TerminalStates() []AssignmentStateCode
	Transitions() []AssignmentTransitionCode
	CanTransition(from AssignmentStateCode, to AssignmentStateCode) bool
	NextStates(from AssignmentStateCode) []AssignmentStateCode
	Mermaid() string
}

type AssignmentFSMServiceProvider interface {
	AssignmentFSM() AssignmentFSM
}

type generatedAssignmentFSM struct{}

type generatedAssignmentFSMServiceProvider struct{}

func GeneratedAssignmentFSM() AssignmentFSM {
	return generatedAssignmentFSM{}
}

func GeneratedAssignmentFSMServiceProvider() AssignmentFSMServiceProvider {
	return generatedAssignmentFSMServiceProvider{}
}

func (generatedAssignmentFSMServiceProvider) AssignmentFSM() AssignmentFSM {
	return generatedAssignmentFSM{}
}

func (generatedAssignmentFSM) Name() string {
	return "assignment"
}

func (generatedAssignmentFSM) States() []AssignmentStateCode {
	return AllAssignmentStateCodes()
}

func (generatedAssignmentFSM) TerminalStates() []AssignmentStateCode {
	return []AssignmentStateCode{
		AssignmentStateCodeCancelled,
		AssignmentStateCodeCompleted,
		AssignmentStateCodeFailed,
	}
}

func (generatedAssignmentFSM) Transitions() []AssignmentTransitionCode {
	return AssignmentTransitionCodes()
}

func (generatedAssignmentFSM) CanTransition(from AssignmentStateCode, to AssignmentStateCode) bool {
	return CanTransitionCode(from, to)
}

func (generatedAssignmentFSM) NextStates(from AssignmentStateCode) []AssignmentStateCode {
	switch from {
	case AssignmentStateCodeQueued:
		return []AssignmentStateCode{
			AssignmentStateCodeQueued,
			AssignmentStateCodeLeased,
			AssignmentStateCodeCancelling,
			AssignmentStateCodeCancelled,
			AssignmentStateCodeFailed,
		}
	case AssignmentStateCodeLeased:
		return []AssignmentStateCode{
			AssignmentStateCodeLeased,
			AssignmentStateCodeReady,
			AssignmentStateCodeRunning,
			AssignmentStateCodeCancelling,
			AssignmentStateCodeCancelled,
			AssignmentStateCodeFailed,
		}
	case AssignmentStateCodeReady:
		return []AssignmentStateCode{
			AssignmentStateCodeReady,
			AssignmentStateCodeRunning,
			AssignmentStateCodeCancelling,
			AssignmentStateCodeCancelled,
			AssignmentStateCodeFailed,
		}
	case AssignmentStateCodeRunning:
		return []AssignmentStateCode{
			AssignmentStateCodeRunning,
			AssignmentStateCodeCancelling,
			AssignmentStateCodeCancelled,
			AssignmentStateCodeCompleted,
			AssignmentStateCodeFailed,
		}
	case AssignmentStateCodeCancelling:
		return []AssignmentStateCode{
			AssignmentStateCodeCancelling,
			AssignmentStateCodeCancelled,
			AssignmentStateCodeFailed,
		}
	case AssignmentStateCodeCancelled:
		return []AssignmentStateCode{
			AssignmentStateCodeCancelled,
		}
	case AssignmentStateCodeCompleted:
		return []AssignmentStateCode{
			AssignmentStateCodeCompleted,
		}
	case AssignmentStateCodeFailed:
		return []AssignmentStateCode{
			AssignmentStateCodeFailed,
		}
	}
	return nil
}

const AssignmentFSMMermaid = `stateDiagram-v2
  [*] --> Queued
  Queued --> Leased
  Queued --> Cancelling
  Queued --> Cancelled
  Queued --> Failed
  Leased --> Ready
  Leased --> Running
  Leased --> Cancelling
  Leased --> Cancelled
  Leased --> Failed
  Ready --> Running
  Ready --> Cancelling
  Ready --> Cancelled
  Ready --> Failed
  Running --> Completed
  Running --> Failed
  Running --> Cancelling
  Running --> Cancelled
  Cancelling --> Cancelled
  Cancelling --> Failed
  Cancelled --> [*]
  Completed --> [*]
  Failed --> [*]
`

func (generatedAssignmentFSM) Mermaid() string {
	return AssignmentFSMMermaid
}
