// Code generated by fsm gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

const AssignmentFSMMermaid = `stateDiagram-v2
  [*] --> Queued
  Queued --> Leased
  Queued --> Cancelling
  Queued --> Cancelled
  Queued --> Failed
  Leased --> Ready
  Leased --> Running
  Leased --> Cancelling
  Leased --> Cancelled
  Leased --> Failed
  Ready --> Running
  Ready --> Cancelling
  Ready --> Cancelled
  Ready --> Failed
  Running --> Completed
  Running --> Failed
  Running --> Cancelling
  Running --> Cancelled
  Cancelling --> Cancelled
  Cancelling --> Failed
  Cancelled --> [*]
  Completed --> [*]
  Failed --> [*]
`

func (generatedAssignmentFSM) Mermaid() string {
	return AssignmentFSMMermaid
}
