// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

var assignmentStateCodeByString = map[AssignmentStateString]AssignmentStateCode{
	AssignmentStateStringQueued:     AssignmentStateCodeQueued,
	AssignmentStateStringLeased:     AssignmentStateCodeLeased,
	AssignmentStateStringReady:      AssignmentStateCodeReady,
	AssignmentStateStringRunning:    AssignmentStateCodeRunning,
	AssignmentStateStringCancelling: AssignmentStateCodeCancelling,
	AssignmentStateStringCancelled:  AssignmentStateCodeCancelled,
	AssignmentStateStringCompleted:  AssignmentStateCodeCompleted,
	AssignmentStateStringFailed:     AssignmentStateCodeFailed,
}
