// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

var pollActionCodeByString = map[PollActionString]PollActionCode{
	PollActionStringNone:   PollActionCodeNone,
	PollActionStringStart:  PollActionCodeStart,
	PollActionStringCancel: PollActionCodeCancel,
	PollActionStringActive: PollActionCodeActive,
}
