// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

var pollActionStringByCode = map[PollActionCode]PollActionString{
	PollActionCodeNone:   PollActionStringNone,
	PollActionCodeStart:  PollActionStringStart,
	PollActionCodeCancel: PollActionStringCancel,
	PollActionCodeActive: PollActionStringActive,
}
