// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

var pollActionAllCodes = []PollActionCode{
	PollActionCodeNone,
	PollActionCodeStart,
	PollActionCodeCancel,
	PollActionCodeActive,
}
