// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

func (code PollActionCode) IsKnown() bool {
	_, ok := pollActionStringByCode[code]
	return ok
}

func (code PollActionCode) StringValue() PollActionString {
	return pollActionStringByCode[code]
}

func (code PollActionCode) String() string {
	return string(code.StringValue())
}

func (code PollActionCode) PollAction() PollAction {
	return PollAction(code.StringValue())
}
