// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

type PollActionCode uint16

type PollActionString string

const (
	PollActionCodeUnknown PollActionCode = iota
	PollActionCodeNone
	PollActionCodeStart
	PollActionCodeCancel
	PollActionCodeActive
)

const (
	PollActionStringNone   PollActionString = "none"
	PollActionStringStart  PollActionString = "start"
	PollActionStringCancel PollActionString = "cancel"
	PollActionStringActive PollActionString = "active"
)

const (
	PollNone   PollAction = PollAction(PollActionStringNone)
	PollStart  PollAction = PollAction(PollActionStringStart)
	PollCancel PollAction = PollAction(PollActionStringCancel)
	PollActive PollAction = PollAction(PollActionStringActive)
)

func (value PollAction) Code() PollActionCode {
	return ParsePollActionCode(string(value))
}

func ParsePollActionCode(value string) PollActionCode {
	switch PollActionString(value) {
	case PollActionStringNone:
		return PollActionCodeNone
	case PollActionStringStart:
		return PollActionCodeStart
	case PollActionStringCancel:
		return PollActionCodeCancel
	case PollActionStringActive:
		return PollActionCodeActive
	default:
		return PollActionCodeUnknown
	}
}

func (code PollActionCode) IsKnown() bool {
	return code >= PollActionCodeNone && code <= PollActionCodeActive
}

func (code PollActionCode) StringValue() PollActionString {
	switch code {
	case PollActionCodeNone:
		return PollActionStringNone
	case PollActionCodeStart:
		return PollActionStringStart
	case PollActionCodeCancel:
		return PollActionStringCancel
	case PollActionCodeActive:
		return PollActionStringActive
	default:
		return PollActionString("")
	}
}

func (code PollActionCode) String() string {
	return string(code.StringValue())
}

func (code PollActionCode) PollAction() PollAction {
	return PollAction(code.StringValue())
}

func (value PollAction) Valid() bool {
	return value.Code().IsKnown()
}

func AllPollActionCodes() []PollActionCode {
	return []PollActionCode{
		PollActionCodeNone,
		PollActionCodeStart,
		PollActionCodeCancel,
		PollActionCodeActive,
	}
}

func AllPollActions() []PollAction {
	codes := AllPollActionCodes()
	out := make([]PollAction, len(codes))
	for index, code := range codes {
		out[index] = code.PollAction()
	}
	return out
}
