// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

const (
	PollActionStringNone   PollActionString = "none"
	PollActionStringStart  PollActionString = "start"
	PollActionStringCancel PollActionString = "cancel"
	PollActionStringActive PollActionString = "active"
)
