// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

const (
	PollActionCodeUnknown PollActionCode = iota
	PollActionCodeNone
	PollActionCodeStart
	PollActionCodeCancel
	PollActionCodeActive
)
