// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

func AllPollActionCodes() []PollActionCode {
	return append([]PollActionCode(nil), pollActionAllCodes...)
}

func AllPollActions() []PollAction {
	codes := AllPollActionCodes()
	out := make([]PollAction, len(codes))
	for index, code := range codes {
		out[index] = code.PollAction()
	}
	return out
}
