// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

func (value PollAction) Code() PollActionCode {
	return ParsePollActionCode(string(value))
}

func ParsePollActionCode(value string) PollActionCode {
	code, ok := pollActionCodeByString[PollActionString(value)]
	if !ok {
		return PollActionCodeUnknown
	}
	return code
}
