// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package assignment

const (
	PollNone   PollAction = PollAction(PollActionStringNone)
	PollStart  PollAction = PollAction(PollActionStringStart)
	PollCancel PollAction = PollAction(PollActionStringCancel)
	PollActive PollAction = PollAction(PollActionStringActive)
)
