package main

const (
	defaultManifest = "docs/20-domain/task-lifecycle.riido.json"
	manifestSchema  = "riido-contracts-task-lifecycle-doc.v1"
	evidenceSchema  = "riido-contracts-task-lifecycle-evidence.v1"
	generatedNotice = "<!-- Generated by go run ./tools/tasklifecycle -write-doc. Do not edit by hand. -->"
)
