package main

const (
	bundleSchemaVersion = "riido-saas-contract-ui-bundle.v1"
	generatedPath       = "contract-ui/src/generated/saasContracts.js"
	fixtureGlob         = "apicontract/fixtures/*.ir.riido.json"
	generatedNotice     = "// Code generated by go run ./tools/contractui generate; DO NOT EDIT.\n"
)
