package main

import (
	"strings"
	"testing"
)

func TestRenderManifestMarksGeneratedDoc(t *testing.T) {
	m := minimalManifest()
	body := renderManifest(m)
	if !strings.Contains(body, "Code generated by go run ./tools/promotionpolicy render") {
		t.Fatalf("missing generated marker: %q", body)
	}
	if !strings.Contains(body, "docs/migration/contracts.md") {
		t.Fatalf("missing migration docs condition: %q", body)
	}
}
