package main

import (
	"fmt"
	"strings"
)

func renderManifest(m manifest) string {
	var b strings.Builder
	b.WriteString("# Contract Promotion Policy\n\n")
	b.WriteString("<!-- Code generated by go run ./tools/promotionpolicy render; DO NOT EDIT. -->\n\n")
	fmt.Fprintf(&b, "> Riido task: %s\n\n", cell(m.RiidoTask))
	fmt.Fprintf(&b, "%s\n\n", cell(m.Summary))
	renderPromotionRule(&b, m)
	renderVersioning(&b, m)
	renderRuntimeTags(&b, m)
	renderBreakingRules(&b, m)
	renderDownstreamRule(&b, m)
	return strings.TrimRight(b.String(), "\n") + "\n"
}
