// Code generated by fsm gen from enumgen/enums.lisp; DO NOT EDIT.

package task

const TaskFSMMermaid = `stateDiagram-v2
  [*] --> Created
  Created --> Queued : TaskQueued
  Queued --> Claimed : TaskClaimed
  Claimed --> Preparing : WorkdirPreparing
  Preparing --> Running : RunStarted
  Running --> Validating : RunReportedDone
  Validating --> PatchReady : ValidationPassed
  PatchReady --> HumanReview : ReviewRequested
  HumanReview --> Completed : HumanApproved
  PatchReady --> Completed : AutoApproved
  Running --> NeedsInput : InputRequested
  NeedsInput --> Running : InputProvided
  Preparing --> Blocked : BlockerRaised
  Running --> Blocked : BlockerRaised
  Blocked --> Running : BlockerResolved
  Blocked --> Queued : BlockerResolvedRequeue
  Validating --> Failed : ValidationFailed
  HumanReview --> ReworkQueued : HumanRejected
  HumanReview --> Cancelled : HumanRejected
  ReworkQueued --> Queued : ReworkAccepted
  Running --> Failed : RuntimePinViolated
  Validating --> Failed : RuntimePinViolated
  Claimed --> Failed : TaskFailed
  Preparing --> Failed : TaskFailed
  Running --> Failed : TaskFailed
  NeedsInput --> Failed : TaskFailed
  Blocked --> Failed : TaskFailed
  Validating --> Failed : TaskFailed
  Created --> Cancelled : TaskCancelled
  Queued --> Cancelled : TaskCancelled
  Claimed --> Cancelled : TaskCancelled
  Preparing --> Cancelled : TaskCancelled
  Running --> Cancelled : TaskCancelled
  NeedsInput --> Cancelled : TaskCancelled
  Blocked --> Cancelled : TaskCancelled
  Validating --> Cancelled : TaskCancelled
  PatchReady --> Cancelled : TaskCancelled
  HumanReview --> Cancelled : TaskCancelled
  ReworkQueued --> Cancelled : TaskCancelled
  Running --> TimedOut : TaskTimedOut
  NeedsInput --> TimedOut : TaskTimedOut
  Blocked --> TimedOut : TaskTimedOut
  Validating --> TimedOut : TaskTimedOut
  HumanReview --> TimedOut : TaskTimedOut
  Completed --> [*]
  Failed --> [*]
  Cancelled --> [*]
  TimedOut --> [*]
`

func (generatedTaskFSM) Mermaid() string {
	return TaskFSMMermaid
}
