// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package task

import (
	"github.com/teamswyg/riido-contracts/ir"
)

var taskTransitionCodeAll = []TaskTransitionCode{
	{From: TaskStateCodeCreated, To: TaskStateCodeQueued, Trigger: ir.EventTypeCodeTaskQueued},
	{From: TaskStateCodeQueued, To: TaskStateCodeClaimed, Trigger: ir.EventTypeCodeTaskClaimed},
	{From: TaskStateCodeClaimed, To: TaskStateCodePreparing, Trigger: ir.EventTypeCodeWorkdirPreparing},
	{From: TaskStateCodePreparing, To: TaskStateCodeRunning, Trigger: ir.EventTypeCodeRunStarted},
	{From: TaskStateCodeRunning, To: TaskStateCodeValidating, Trigger: ir.EventTypeCodeRunReportedDone},
	{From: TaskStateCodeValidating, To: TaskStateCodePatchReady, Trigger: ir.EventTypeCodeValidationPassed},
	{From: TaskStateCodePatchReady, To: TaskStateCodeHumanReview, Trigger: ir.EventTypeCodeReviewRequested},
	{From: TaskStateCodeHumanReview, To: TaskStateCodeCompleted, Trigger: ir.EventTypeCodeHumanApproved},
	{From: TaskStateCodePatchReady, To: TaskStateCodeCompleted, Trigger: ir.EventTypeCodeAutoApproved},
	{From: TaskStateCodeRunning, To: TaskStateCodeNeedsInput, Trigger: ir.EventTypeCodeInputRequested},
	{From: TaskStateCodeNeedsInput, To: TaskStateCodeRunning, Trigger: ir.EventTypeCodeInputProvided},
	{From: TaskStateCodePreparing, To: TaskStateCodeBlocked, Trigger: ir.EventTypeCodeBlockerRaised},
	{From: TaskStateCodeRunning, To: TaskStateCodeBlocked, Trigger: ir.EventTypeCodeBlockerRaised},
	{From: TaskStateCodeBlocked, To: TaskStateCodeRunning, Trigger: ir.EventTypeCodeBlockerResolved},
	{From: TaskStateCodeBlocked, To: TaskStateCodeQueued, Trigger: ir.EventTypeCodeBlockerResolvedRequeue},
	{From: TaskStateCodeValidating, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeValidationFailed},
	{From: TaskStateCodeHumanReview, To: TaskStateCodeReworkQueued, Trigger: ir.EventTypeCodeHumanRejected},
	{From: TaskStateCodeHumanReview, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeHumanRejected},
	{From: TaskStateCodeReworkQueued, To: TaskStateCodeQueued, Trigger: ir.EventTypeCodeReworkAccepted},
	{From: TaskStateCodeRunning, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeRuntimePinViolated},
	{From: TaskStateCodeValidating, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeRuntimePinViolated},
	{From: TaskStateCodeClaimed, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeTaskFailed},
	{From: TaskStateCodePreparing, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeTaskFailed},
	{From: TaskStateCodeRunning, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeTaskFailed},
	{From: TaskStateCodeNeedsInput, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeTaskFailed},
	{From: TaskStateCodeBlocked, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeTaskFailed},
	{From: TaskStateCodeValidating, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeTaskFailed},
	{From: TaskStateCodeCreated, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled},
	{From: TaskStateCodeQueued, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled},
	{From: TaskStateCodeClaimed, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled},
	{From: TaskStateCodePreparing, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled},
	{From: TaskStateCodeRunning, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled},
	{From: TaskStateCodeNeedsInput, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled},
	{From: TaskStateCodeBlocked, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled},
	{From: TaskStateCodeValidating, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled},
	{From: TaskStateCodePatchReady, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled},
	{From: TaskStateCodeHumanReview, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled},
	{From: TaskStateCodeReworkQueued, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled},
	{From: TaskStateCodeRunning, To: TaskStateCodeTimedOut, Trigger: ir.EventTypeCodeTaskTimedOut},
	{From: TaskStateCodeNeedsInput, To: TaskStateCodeTimedOut, Trigger: ir.EventTypeCodeTaskTimedOut},
	{From: TaskStateCodeBlocked, To: TaskStateCodeTimedOut, Trigger: ir.EventTypeCodeTaskTimedOut},
	{From: TaskStateCodeValidating, To: TaskStateCodeTimedOut, Trigger: ir.EventTypeCodeTaskTimedOut},
	{From: TaskStateCodeHumanReview, To: TaskStateCodeTimedOut, Trigger: ir.EventTypeCodeTaskTimedOut},
}

func LegalTransitionCodes() []TaskTransitionCode {
	return append([]TaskTransitionCode(nil), taskTransitionCodeAll...)
}
