// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package task

var taskStateCodeByString = map[TaskStateString]TaskStateCode{
	TaskStateStringCreated:      TaskStateCodeCreated,
	TaskStateStringQueued:       TaskStateCodeQueued,
	TaskStateStringClaimed:      TaskStateCodeClaimed,
	TaskStateStringPreparing:    TaskStateCodePreparing,
	TaskStateStringRunning:      TaskStateCodeRunning,
	TaskStateStringNeedsInput:   TaskStateCodeNeedsInput,
	TaskStateStringBlocked:      TaskStateCodeBlocked,
	TaskStateStringValidating:   TaskStateCodeValidating,
	TaskStateStringPatchReady:   TaskStateCodePatchReady,
	TaskStateStringHumanReview:  TaskStateCodeHumanReview,
	TaskStateStringReworkQueued: TaskStateCodeReworkQueued,
	TaskStateStringCompleted:    TaskStateCodeCompleted,
	TaskStateStringFailed:       TaskStateCodeFailed,
	TaskStateStringCancelled:    TaskStateCodeCancelled,
	TaskStateStringTimedOut:     TaskStateCodeTimedOut,
}
