// Code generated by fsm gen from enumgen/enums.lisp; DO NOT EDIT.

package task

func GeneratedTaskFSM() TaskFSM {
	return generatedTaskFSM{}
}

func GeneratedTaskFSMServiceProvider() TaskFSMServiceProvider {
	return generatedTaskFSMServiceProvider{}
}

func (generatedTaskFSMServiceProvider) TaskFSM() TaskFSM {
	return generatedTaskFSM{}
}

func (generatedTaskFSM) Name() string {
	return "task"
}

func (generatedTaskFSM) TypeUnion() TaskFSMTypeUnion {
	return TaskFSMTypeUnionTaskLifecycleFSM
}
