// Code generated by fsm gen from enumgen/enums.lisp; DO NOT EDIT.

package task

import (
	"github.com/teamswyg/riido-contracts/ir"
)

type TaskFSMTypeUnion string

const (
	TaskFSMTypeUnionTaskLifecycleFSM TaskFSMTypeUnion = "TaskLifecycleFSM"
)

type TaskFSMPointKind uint8

const (
	TaskFSMPointUnknown TaskFSMPointKind = iota
	TaskFSMPointStart
	TaskFSMPointIntermediate
	TaskFSMPointEnd
)

type TaskFSM interface {
	Name() string
	TypeUnion() TaskFSMTypeUnion
	States() []TaskStateCode
	StartStates() []TaskStateCode
	EndStates() []TaskStateCode
	TerminalStates() []TaskStateCode
	Transitions() []TaskTransitionCode
	PointKind(state TaskStateCode) TaskFSMPointKind
	IsStartState(state TaskStateCode) bool
	IsEndState(state TaskStateCode) bool
	CanTransition(from TaskStateCode, to TaskStateCode, trigger ir.EventTypeCode) bool
	NextStates(from TaskStateCode, trigger ir.EventTypeCode) []TaskStateCode
	Mermaid() string
}

type TaskFSMServiceProvider interface {
	TaskFSM() TaskFSM
}

type generatedTaskFSM struct{}

type generatedTaskFSMServiceProvider struct{}
