// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package task

type TaskStateCode uint16

type TaskStateString string

const (
	TaskStateCodeUnknown TaskStateCode = iota
	TaskStateCodeCreated
	TaskStateCodeQueued
	TaskStateCodeClaimed
	TaskStateCodePreparing
	TaskStateCodeRunning
	TaskStateCodeNeedsInput
	TaskStateCodeBlocked
	TaskStateCodeValidating
	TaskStateCodePatchReady
	TaskStateCodeHumanReview
	TaskStateCodeReworkQueued
	TaskStateCodeCompleted
	TaskStateCodeFailed
	TaskStateCodeCancelled
	TaskStateCodeTimedOut
)

const (
	TaskStateStringCreated      TaskStateString = "Created"
	TaskStateStringQueued       TaskStateString = "Queued"
	TaskStateStringClaimed      TaskStateString = "Claimed"
	TaskStateStringPreparing    TaskStateString = "Preparing"
	TaskStateStringRunning      TaskStateString = "Running"
	TaskStateStringNeedsInput   TaskStateString = "NeedsInput"
	TaskStateStringBlocked      TaskStateString = "Blocked"
	TaskStateStringValidating   TaskStateString = "Validating"
	TaskStateStringPatchReady   TaskStateString = "PatchReady"
	TaskStateStringHumanReview  TaskStateString = "HumanReview"
	TaskStateStringReworkQueued TaskStateString = "ReworkQueued"
	TaskStateStringCompleted    TaskStateString = "Completed"
	TaskStateStringFailed       TaskStateString = "Failed"
	TaskStateStringCancelled    TaskStateString = "Cancelled"
	TaskStateStringTimedOut     TaskStateString = "TimedOut"
)

const (
	StateCreated      TaskState = TaskState(TaskStateStringCreated)
	StateQueued       TaskState = TaskState(TaskStateStringQueued)
	StateClaimed      TaskState = TaskState(TaskStateStringClaimed)
	StatePreparing    TaskState = TaskState(TaskStateStringPreparing)
	StateRunning      TaskState = TaskState(TaskStateStringRunning)
	StateNeedsInput   TaskState = TaskState(TaskStateStringNeedsInput)
	StateBlocked      TaskState = TaskState(TaskStateStringBlocked)
	StateValidating   TaskState = TaskState(TaskStateStringValidating)
	StatePatchReady   TaskState = TaskState(TaskStateStringPatchReady)
	StateHumanReview  TaskState = TaskState(TaskStateStringHumanReview)
	StateReworkQueued TaskState = TaskState(TaskStateStringReworkQueued)
	StateCompleted    TaskState = TaskState(TaskStateStringCompleted)
	StateFailed       TaskState = TaskState(TaskStateStringFailed)
	StateCancelled    TaskState = TaskState(TaskStateStringCancelled)
	StateTimedOut     TaskState = TaskState(TaskStateStringTimedOut)
)

func (value TaskState) Code() TaskStateCode {
	return ParseTaskStateCode(string(value))
}

func ParseTaskStateCode(value string) TaskStateCode {
	switch TaskStateString(value) {
	case TaskStateStringCreated:
		return TaskStateCodeCreated
	case TaskStateStringQueued:
		return TaskStateCodeQueued
	case TaskStateStringClaimed:
		return TaskStateCodeClaimed
	case TaskStateStringPreparing:
		return TaskStateCodePreparing
	case TaskStateStringRunning:
		return TaskStateCodeRunning
	case TaskStateStringNeedsInput:
		return TaskStateCodeNeedsInput
	case TaskStateStringBlocked:
		return TaskStateCodeBlocked
	case TaskStateStringValidating:
		return TaskStateCodeValidating
	case TaskStateStringPatchReady:
		return TaskStateCodePatchReady
	case TaskStateStringHumanReview:
		return TaskStateCodeHumanReview
	case TaskStateStringReworkQueued:
		return TaskStateCodeReworkQueued
	case TaskStateStringCompleted:
		return TaskStateCodeCompleted
	case TaskStateStringFailed:
		return TaskStateCodeFailed
	case TaskStateStringCancelled:
		return TaskStateCodeCancelled
	case TaskStateStringTimedOut:
		return TaskStateCodeTimedOut
	default:
		return TaskStateCodeUnknown
	}
}

func (code TaskStateCode) IsKnown() bool {
	return code >= TaskStateCodeCreated && code <= TaskStateCodeTimedOut
}

func (code TaskStateCode) StringValue() TaskStateString {
	switch code {
	case TaskStateCodeCreated:
		return TaskStateStringCreated
	case TaskStateCodeQueued:
		return TaskStateStringQueued
	case TaskStateCodeClaimed:
		return TaskStateStringClaimed
	case TaskStateCodePreparing:
		return TaskStateStringPreparing
	case TaskStateCodeRunning:
		return TaskStateStringRunning
	case TaskStateCodeNeedsInput:
		return TaskStateStringNeedsInput
	case TaskStateCodeBlocked:
		return TaskStateStringBlocked
	case TaskStateCodeValidating:
		return TaskStateStringValidating
	case TaskStateCodePatchReady:
		return TaskStateStringPatchReady
	case TaskStateCodeHumanReview:
		return TaskStateStringHumanReview
	case TaskStateCodeReworkQueued:
		return TaskStateStringReworkQueued
	case TaskStateCodeCompleted:
		return TaskStateStringCompleted
	case TaskStateCodeFailed:
		return TaskStateStringFailed
	case TaskStateCodeCancelled:
		return TaskStateStringCancelled
	case TaskStateCodeTimedOut:
		return TaskStateStringTimedOut
	default:
		return TaskStateString("")
	}
}

func (code TaskStateCode) String() string {
	return string(code.StringValue())
}

func (code TaskStateCode) TaskState() TaskState {
	return TaskState(code.StringValue())
}

func (value TaskState) Valid() bool {
	return value.Code().IsKnown()
}

func AllTaskStateCodes() []TaskStateCode {
	return []TaskStateCode{
		TaskStateCodeCreated,
		TaskStateCodeQueued,
		TaskStateCodeClaimed,
		TaskStateCodePreparing,
		TaskStateCodeRunning,
		TaskStateCodeNeedsInput,
		TaskStateCodeBlocked,
		TaskStateCodeValidating,
		TaskStateCodePatchReady,
		TaskStateCodeHumanReview,
		TaskStateCodeReworkQueued,
		TaskStateCodeCompleted,
		TaskStateCodeFailed,
		TaskStateCodeCancelled,
		TaskStateCodeTimedOut,
	}
}

func AllStates() []TaskState {
	codes := AllTaskStateCodes()
	out := make([]TaskState, len(codes))
	for index, code := range codes {
		out[index] = code.TaskState()
	}
	return out
}

func (code TaskStateCode) IsTerminal() bool {
	switch code {
	case TaskStateCodeCompleted, TaskStateCodeFailed, TaskStateCodeCancelled, TaskStateCodeTimedOut:
		return true
	default:
		return false
	}
}

func (value TaskState) IsTerminal() bool {
	return value.Code().IsTerminal()
}

func (code TaskStateCode) IsActive() bool {
	switch code {
	case TaskStateCodeRunning, TaskStateCodeValidating:
		return true
	default:
		return false
	}
}

func (value TaskState) IsActive() bool {
	return value.Code().IsActive()
}
