// Code generated by fsm gen from enumgen/enums.lisp; DO NOT EDIT.

package task

import (
	"github.com/teamswyg/riido-contracts/ir"
)

type TaskFSMTypeUnion string

const (
	TaskFSMTypeUnionTaskLifecycleFSM TaskFSMTypeUnion = "TaskLifecycleFSM"
)

type TaskFSMPointKind uint8

const (
	TaskFSMPointUnknown TaskFSMPointKind = iota
	TaskFSMPointStart
	TaskFSMPointIntermediate
	TaskFSMPointEnd
)

type TaskFSM interface {
	Name() string
	TypeUnion() TaskFSMTypeUnion
	States() []TaskStateCode
	StartStates() []TaskStateCode
	EndStates() []TaskStateCode
	TerminalStates() []TaskStateCode
	Transitions() []TaskTransitionCode
	PointKind(state TaskStateCode) TaskFSMPointKind
	IsStartState(state TaskStateCode) bool
	IsEndState(state TaskStateCode) bool
	CanTransition(from TaskStateCode, to TaskStateCode, trigger ir.EventTypeCode) bool
	NextStates(from TaskStateCode, trigger ir.EventTypeCode) []TaskStateCode
	Mermaid() string
}

type TaskFSMServiceProvider interface {
	TaskFSM() TaskFSM
}

type generatedTaskFSM struct{}

type generatedTaskFSMServiceProvider struct{}

func GeneratedTaskFSM() TaskFSM {
	return generatedTaskFSM{}
}

func GeneratedTaskFSMServiceProvider() TaskFSMServiceProvider {
	return generatedTaskFSMServiceProvider{}
}

func (generatedTaskFSMServiceProvider) TaskFSM() TaskFSM {
	return generatedTaskFSM{}
}

func (generatedTaskFSM) Name() string {
	return "task"
}

func (generatedTaskFSM) TypeUnion() TaskFSMTypeUnion {
	return TaskFSMTypeUnionTaskLifecycleFSM
}

func (generatedTaskFSM) States() []TaskStateCode {
	return AllTaskStateCodes()
}

func (generatedTaskFSM) StartStates() []TaskStateCode {
	return []TaskStateCode{
		TaskStateCodeCreated,
	}
}

func (generatedTaskFSM) EndStates() []TaskStateCode {
	return []TaskStateCode{
		TaskStateCodeCompleted,
		TaskStateCodeFailed,
		TaskStateCodeCancelled,
		TaskStateCodeTimedOut,
	}
}

func (generatedTaskFSM) TerminalStates() []TaskStateCode {
	return []TaskStateCode{
		TaskStateCodeCompleted,
		TaskStateCodeFailed,
		TaskStateCodeCancelled,
		TaskStateCodeTimedOut,
	}
}

func (generatedTaskFSM) Transitions() []TaskTransitionCode {
	return LegalTransitionCodes()
}

func (fsm generatedTaskFSM) PointKind(state TaskStateCode) TaskFSMPointKind {
	switch {
	case fsm.IsStartState(state):
		return TaskFSMPointStart
	case fsm.IsEndState(state):
		return TaskFSMPointEnd
	case state.IsKnown():
		return TaskFSMPointIntermediate
	default:
		return TaskFSMPointUnknown
	}
}

func (generatedTaskFSM) IsStartState(state TaskStateCode) bool {
	switch state {
	case TaskStateCodeCreated:
		return true
	default:
		return false
	}
}

func (generatedTaskFSM) IsEndState(state TaskStateCode) bool {
	switch state {
	case TaskStateCodeCompleted:
		return true
	case TaskStateCodeFailed:
		return true
	case TaskStateCodeCancelled:
		return true
	case TaskStateCodeTimedOut:
		return true
	default:
		return false
	}
}

func (generatedTaskFSM) CanTransition(from TaskStateCode, to TaskStateCode, trigger ir.EventTypeCode) bool {
	return ValidateTransitionCode(from, to, trigger)
}

func (generatedTaskFSM) NextStates(from TaskStateCode, trigger ir.EventTypeCode) []TaskStateCode {
	switch from {
	case TaskStateCodeCreated:
		switch trigger {
		case ir.EventTypeCodeTaskQueued:
			return []TaskStateCode{
				TaskStateCodeQueued,
			}
		case ir.EventTypeCodeTaskCancelled:
			return []TaskStateCode{
				TaskStateCodeCancelled,
			}
		}
	case TaskStateCodeQueued:
		switch trigger {
		case ir.EventTypeCodeTaskClaimed:
			return []TaskStateCode{
				TaskStateCodeClaimed,
			}
		case ir.EventTypeCodeTaskCancelled:
			return []TaskStateCode{
				TaskStateCodeCancelled,
			}
		}
	case TaskStateCodeClaimed:
		switch trigger {
		case ir.EventTypeCodeWorkdirPreparing:
			return []TaskStateCode{
				TaskStateCodePreparing,
			}
		case ir.EventTypeCodeTaskCancelled:
			return []TaskStateCode{
				TaskStateCodeCancelled,
			}
		case ir.EventTypeCodeTaskFailed:
			return []TaskStateCode{
				TaskStateCodeFailed,
			}
		}
	case TaskStateCodePreparing:
		switch trigger {
		case ir.EventTypeCodeRunStarted:
			return []TaskStateCode{
				TaskStateCodeRunning,
			}
		case ir.EventTypeCodeBlockerRaised:
			return []TaskStateCode{
				TaskStateCodeBlocked,
			}
		case ir.EventTypeCodeTaskCancelled:
			return []TaskStateCode{
				TaskStateCodeCancelled,
			}
		case ir.EventTypeCodeTaskFailed:
			return []TaskStateCode{
				TaskStateCodeFailed,
			}
		}
	case TaskStateCodeRunning:
		switch trigger {
		case ir.EventTypeCodeInputRequested:
			return []TaskStateCode{
				TaskStateCodeNeedsInput,
			}
		case ir.EventTypeCodeBlockerRaised:
			return []TaskStateCode{
				TaskStateCodeBlocked,
			}
		case ir.EventTypeCodeRunReportedDone:
			return []TaskStateCode{
				TaskStateCodeValidating,
			}
		case ir.EventTypeCodeTaskCancelled:
			return []TaskStateCode{
				TaskStateCodeCancelled,
			}
		case ir.EventTypeCodeTaskTimedOut:
			return []TaskStateCode{
				TaskStateCodeTimedOut,
			}
		case ir.EventTypeCodeRuntimePinViolated:
			return []TaskStateCode{
				TaskStateCodeFailed,
			}
		case ir.EventTypeCodeTaskFailed:
			return []TaskStateCode{
				TaskStateCodeFailed,
			}
		}
	case TaskStateCodeNeedsInput:
		switch trigger {
		case ir.EventTypeCodeInputProvided:
			return []TaskStateCode{
				TaskStateCodeRunning,
			}
		case ir.EventTypeCodeTaskCancelled:
			return []TaskStateCode{
				TaskStateCodeCancelled,
			}
		case ir.EventTypeCodeTaskTimedOut:
			return []TaskStateCode{
				TaskStateCodeTimedOut,
			}
		case ir.EventTypeCodeTaskFailed:
			return []TaskStateCode{
				TaskStateCodeFailed,
			}
		}
	case TaskStateCodeBlocked:
		switch trigger {
		case ir.EventTypeCodeBlockerResolved:
			return []TaskStateCode{
				TaskStateCodeRunning,
			}
		case ir.EventTypeCodeBlockerResolvedRequeue:
			return []TaskStateCode{
				TaskStateCodeQueued,
			}
		case ir.EventTypeCodeTaskCancelled:
			return []TaskStateCode{
				TaskStateCodeCancelled,
			}
		case ir.EventTypeCodeTaskTimedOut:
			return []TaskStateCode{
				TaskStateCodeTimedOut,
			}
		case ir.EventTypeCodeTaskFailed:
			return []TaskStateCode{
				TaskStateCodeFailed,
			}
		}
	case TaskStateCodeValidating:
		switch trigger {
		case ir.EventTypeCodeValidationPassed:
			return []TaskStateCode{
				TaskStateCodePatchReady,
			}
		case ir.EventTypeCodeValidationFailed:
			return []TaskStateCode{
				TaskStateCodeFailed,
			}
		case ir.EventTypeCodeTaskCancelled:
			return []TaskStateCode{
				TaskStateCodeCancelled,
			}
		case ir.EventTypeCodeTaskTimedOut:
			return []TaskStateCode{
				TaskStateCodeTimedOut,
			}
		case ir.EventTypeCodeRuntimePinViolated:
			return []TaskStateCode{
				TaskStateCodeFailed,
			}
		case ir.EventTypeCodeTaskFailed:
			return []TaskStateCode{
				TaskStateCodeFailed,
			}
		}
	case TaskStateCodePatchReady:
		switch trigger {
		case ir.EventTypeCodeReviewRequested:
			return []TaskStateCode{
				TaskStateCodeHumanReview,
			}
		case ir.EventTypeCodeAutoApproved:
			return []TaskStateCode{
				TaskStateCodeCompleted,
			}
		case ir.EventTypeCodeTaskCancelled:
			return []TaskStateCode{
				TaskStateCodeCancelled,
			}
		}
	case TaskStateCodeHumanReview:
		switch trigger {
		case ir.EventTypeCodeHumanApproved:
			return []TaskStateCode{
				TaskStateCodeCompleted,
			}
		case ir.EventTypeCodeHumanRejected:
			return []TaskStateCode{
				TaskStateCodeReworkQueued,
				TaskStateCodeCancelled,
			}
		case ir.EventTypeCodeTaskCancelled:
			return []TaskStateCode{
				TaskStateCodeCancelled,
			}
		case ir.EventTypeCodeTaskTimedOut:
			return []TaskStateCode{
				TaskStateCodeTimedOut,
			}
		}
	case TaskStateCodeReworkQueued:
		switch trigger {
		case ir.EventTypeCodeReworkAccepted:
			return []TaskStateCode{
				TaskStateCodeQueued,
			}
		case ir.EventTypeCodeTaskCancelled:
			return []TaskStateCode{
				TaskStateCodeCancelled,
			}
		}
	}
	return nil
}

const TaskFSMMermaid = `stateDiagram-v2
  [*] --> Created
  Created --> Queued : TaskQueued
  Queued --> Claimed : TaskClaimed
  Claimed --> Preparing : WorkdirPreparing
  Preparing --> Running : RunStarted
  Running --> Validating : RunReportedDone
  Validating --> PatchReady : ValidationPassed
  PatchReady --> HumanReview : ReviewRequested
  HumanReview --> Completed : HumanApproved
  PatchReady --> Completed : AutoApproved
  Running --> NeedsInput : InputRequested
  NeedsInput --> Running : InputProvided
  Preparing --> Blocked : BlockerRaised
  Running --> Blocked : BlockerRaised
  Blocked --> Running : BlockerResolved
  Blocked --> Queued : BlockerResolvedRequeue
  Validating --> Failed : ValidationFailed
  HumanReview --> ReworkQueued : HumanRejected
  HumanReview --> Cancelled : HumanRejected
  ReworkQueued --> Queued : ReworkAccepted
  Running --> Failed : RuntimePinViolated
  Validating --> Failed : RuntimePinViolated
  Claimed --> Failed : TaskFailed
  Preparing --> Failed : TaskFailed
  Running --> Failed : TaskFailed
  NeedsInput --> Failed : TaskFailed
  Blocked --> Failed : TaskFailed
  Validating --> Failed : TaskFailed
  Created --> Cancelled : TaskCancelled
  Queued --> Cancelled : TaskCancelled
  Claimed --> Cancelled : TaskCancelled
  Preparing --> Cancelled : TaskCancelled
  Running --> Cancelled : TaskCancelled
  NeedsInput --> Cancelled : TaskCancelled
  Blocked --> Cancelled : TaskCancelled
  Validating --> Cancelled : TaskCancelled
  PatchReady --> Cancelled : TaskCancelled
  HumanReview --> Cancelled : TaskCancelled
  ReworkQueued --> Cancelled : TaskCancelled
  Running --> TimedOut : TaskTimedOut
  NeedsInput --> TimedOut : TaskTimedOut
  Blocked --> TimedOut : TaskTimedOut
  Validating --> TimedOut : TaskTimedOut
  HumanReview --> TimedOut : TaskTimedOut
  Completed --> [*]
  Failed --> [*]
  Cancelled --> [*]
  TimedOut --> [*]
`

func (generatedTaskFSM) Mermaid() string {
	return TaskFSMMermaid
}
