// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package task

import (
	"github.com/teamswyg/riido-contracts/ir"
)

type TaskTransitionCode struct {
	From    TaskStateCode
	To      TaskStateCode
	Trigger ir.EventTypeCode
}
