// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package task

const (
	TaskStateCodeUnknown TaskStateCode = iota
	TaskStateCodeCreated
	TaskStateCodeQueued
	TaskStateCodeClaimed
	TaskStateCodePreparing
	TaskStateCodeRunning
	TaskStateCodeNeedsInput
	TaskStateCodeBlocked
	TaskStateCodeValidating
	TaskStateCodePatchReady
	TaskStateCodeHumanReview
	TaskStateCodeReworkQueued
	TaskStateCodeCompleted
	TaskStateCodeFailed
	TaskStateCodeCancelled
	TaskStateCodeTimedOut
)
