// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package task

var taskStateStringByCode = map[TaskStateCode]TaskStateString{
	TaskStateCodeCreated:      TaskStateStringCreated,
	TaskStateCodeQueued:       TaskStateStringQueued,
	TaskStateCodeClaimed:      TaskStateStringClaimed,
	TaskStateCodePreparing:    TaskStateStringPreparing,
	TaskStateCodeRunning:      TaskStateStringRunning,
	TaskStateCodeNeedsInput:   TaskStateStringNeedsInput,
	TaskStateCodeBlocked:      TaskStateStringBlocked,
	TaskStateCodeValidating:   TaskStateStringValidating,
	TaskStateCodePatchReady:   TaskStateStringPatchReady,
	TaskStateCodeHumanReview:  TaskStateStringHumanReview,
	TaskStateCodeReworkQueued: TaskStateStringReworkQueued,
	TaskStateCodeCompleted:    TaskStateStringCompleted,
	TaskStateCodeFailed:       TaskStateStringFailed,
	TaskStateCodeCancelled:    TaskStateStringCancelled,
	TaskStateCodeTimedOut:     TaskStateStringTimedOut,
}
