// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package task

const (
	TaskStateStringCreated      TaskStateString = "Created"
	TaskStateStringQueued       TaskStateString = "Queued"
	TaskStateStringClaimed      TaskStateString = "Claimed"
	TaskStateStringPreparing    TaskStateString = "Preparing"
	TaskStateStringRunning      TaskStateString = "Running"
	TaskStateStringNeedsInput   TaskStateString = "NeedsInput"
	TaskStateStringBlocked      TaskStateString = "Blocked"
	TaskStateStringValidating   TaskStateString = "Validating"
	TaskStateStringPatchReady   TaskStateString = "PatchReady"
	TaskStateStringHumanReview  TaskStateString = "HumanReview"
	TaskStateStringReworkQueued TaskStateString = "ReworkQueued"
	TaskStateStringCompleted    TaskStateString = "Completed"
	TaskStateStringFailed       TaskStateString = "Failed"
	TaskStateStringCancelled    TaskStateString = "Cancelled"
	TaskStateStringTimedOut     TaskStateString = "TimedOut"
)
