// Code generated by fsm gen from enumgen/enums.lisp; DO NOT EDIT.

package task

var taskFSMStartStates = []TaskStateCode{
	TaskStateCodeCreated,
}

var taskFSMEndStates = []TaskStateCode{
	TaskStateCodeCompleted,
	TaskStateCodeFailed,
	TaskStateCodeCancelled,
	TaskStateCodeTimedOut,
}

func (generatedTaskFSM) States() []TaskStateCode {
	return AllTaskStateCodes()
}

func (generatedTaskFSM) StartStates() []TaskStateCode {
	return append([]TaskStateCode(nil), taskFSMStartStates...)
}

func (generatedTaskFSM) EndStates() []TaskStateCode {
	return append([]TaskStateCode(nil), taskFSMEndStates...)
}

func (generatedTaskFSM) TerminalStates() []TaskStateCode {
	return append([]TaskStateCode(nil), taskFSMEndStates...)
}

func (generatedTaskFSM) Transitions() []TaskTransitionCode {
	return LegalTransitionCodes()
}
