// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package task

func (value TaskState) Code() TaskStateCode {
	return ParseTaskStateCode(string(value))
}

func ParseTaskStateCode(value string) TaskStateCode {
	code, ok := taskStateCodeByString[TaskStateString(value)]
	if !ok {
		return TaskStateCodeUnknown
	}
	return code
}
