// Code generated by fsm gen from enumgen/enums.lisp; DO NOT EDIT.

package task

var taskFSMStartStateSet = map[TaskStateCode]bool{
	TaskStateCodeCreated: true,
}

var taskFSMEndStateSet = map[TaskStateCode]bool{
	TaskStateCodeCompleted: true,
	TaskStateCodeFailed:    true,
	TaskStateCodeCancelled: true,
	TaskStateCodeTimedOut:  true,
}

func (fsm generatedTaskFSM) PointKind(state TaskStateCode) TaskFSMPointKind {
	switch {
	case fsm.IsStartState(state):
		return TaskFSMPointStart
	case fsm.IsEndState(state):
		return TaskFSMPointEnd
	case state.IsKnown():
		return TaskFSMPointIntermediate
	default:
		return TaskFSMPointUnknown
	}
}

func (generatedTaskFSM) IsStartState(state TaskStateCode) bool {
	return taskFSMStartStateSet[state]
}

func (generatedTaskFSM) IsEndState(state TaskStateCode) bool {
	return taskFSMEndStateSet[state]
}
