// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package task

func AllTaskStateCodes() []TaskStateCode {
	return append([]TaskStateCode(nil), taskStateAllCodes...)
}

func AllStates() []TaskState {
	codes := AllTaskStateCodes()
	out := make([]TaskState, len(codes))
	for index, code := range codes {
		out[index] = code.TaskState()
	}
	return out
}
