// Code generated by fsm gen from enumgen/enums.lisp; DO NOT EDIT.

package task

import (
	"github.com/teamswyg/riido-contracts/ir"
)

func (generatedTaskFSM) CanTransition(from TaskStateCode, to TaskStateCode, trigger ir.EventTypeCode) bool {
	return ValidateTransitionCode(from, to, trigger)
}

func (generatedTaskFSM) NextStates(from TaskStateCode, trigger ir.EventTypeCode) []TaskStateCode {
	states := taskFSMNextStates[taskFSMNextStateKey{From: from, Trigger: trigger}]
	return append([]TaskStateCode(nil), states...)
}
