// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package task

const (
	StateCreated      TaskState = TaskState(TaskStateStringCreated)
	StateQueued       TaskState = TaskState(TaskStateStringQueued)
	StateClaimed      TaskState = TaskState(TaskStateStringClaimed)
	StatePreparing    TaskState = TaskState(TaskStateStringPreparing)
	StateRunning      TaskState = TaskState(TaskStateStringRunning)
	StateNeedsInput   TaskState = TaskState(TaskStateStringNeedsInput)
	StateBlocked      TaskState = TaskState(TaskStateStringBlocked)
	StateValidating   TaskState = TaskState(TaskStateStringValidating)
	StatePatchReady   TaskState = TaskState(TaskStateStringPatchReady)
	StateHumanReview  TaskState = TaskState(TaskStateStringHumanReview)
	StateReworkQueued TaskState = TaskState(TaskStateStringReworkQueued)
	StateCompleted    TaskState = TaskState(TaskStateStringCompleted)
	StateFailed       TaskState = TaskState(TaskStateStringFailed)
	StateCancelled    TaskState = TaskState(TaskStateStringCancelled)
	StateTimedOut     TaskState = TaskState(TaskStateStringTimedOut)
)
