// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package task

func (code TaskStateCode) IsTerminal() bool {
	switch code {
	case TaskStateCodeCompleted, TaskStateCodeFailed, TaskStateCodeCancelled, TaskStateCodeTimedOut:
		return true
	default:
		return false
	}
}

func (value TaskState) IsTerminal() bool {
	return value.Code().IsTerminal()
}

func (code TaskStateCode) IsActive() bool {
	switch code {
	case TaskStateCodeRunning, TaskStateCodeValidating:
		return true
	default:
		return false
	}
}

func (value TaskState) IsActive() bool {
	return value.Code().IsActive()
}
