// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package task

import (
	"github.com/teamswyg/riido-contracts/ir"
)

var taskTransitionCodeAllowed = map[TaskTransitionCode]bool{
	{From: TaskStateCodeCreated, To: TaskStateCodeQueued, Trigger: ir.EventTypeCodeTaskQueued}:              true,
	{From: TaskStateCodeQueued, To: TaskStateCodeClaimed, Trigger: ir.EventTypeCodeTaskClaimed}:             true,
	{From: TaskStateCodeClaimed, To: TaskStateCodePreparing, Trigger: ir.EventTypeCodeWorkdirPreparing}:     true,
	{From: TaskStateCodePreparing, To: TaskStateCodeRunning, Trigger: ir.EventTypeCodeRunStarted}:           true,
	{From: TaskStateCodeRunning, To: TaskStateCodeValidating, Trigger: ir.EventTypeCodeRunReportedDone}:     true,
	{From: TaskStateCodeValidating, To: TaskStateCodePatchReady, Trigger: ir.EventTypeCodeValidationPassed}: true,
	{From: TaskStateCodePatchReady, To: TaskStateCodeHumanReview, Trigger: ir.EventTypeCodeReviewRequested}: true,
	{From: TaskStateCodeHumanReview, To: TaskStateCodeCompleted, Trigger: ir.EventTypeCodeHumanApproved}:    true,
	{From: TaskStateCodePatchReady, To: TaskStateCodeCompleted, Trigger: ir.EventTypeCodeAutoApproved}:      true,
	{From: TaskStateCodeRunning, To: TaskStateCodeNeedsInput, Trigger: ir.EventTypeCodeInputRequested}:      true,
	{From: TaskStateCodeNeedsInput, To: TaskStateCodeRunning, Trigger: ir.EventTypeCodeInputProvided}:       true,
	{From: TaskStateCodePreparing, To: TaskStateCodeBlocked, Trigger: ir.EventTypeCodeBlockerRaised}:        true,
	{From: TaskStateCodeRunning, To: TaskStateCodeBlocked, Trigger: ir.EventTypeCodeBlockerRaised}:          true,
	{From: TaskStateCodeBlocked, To: TaskStateCodeRunning, Trigger: ir.EventTypeCodeBlockerResolved}:        true,
	{From: TaskStateCodeBlocked, To: TaskStateCodeQueued, Trigger: ir.EventTypeCodeBlockerResolvedRequeue}:  true,
	{From: TaskStateCodeValidating, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeValidationFailed}:     true,
	{From: TaskStateCodeHumanReview, To: TaskStateCodeReworkQueued, Trigger: ir.EventTypeCodeHumanRejected}: true,
	{From: TaskStateCodeHumanReview, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeHumanRejected}:    true,
	{From: TaskStateCodeReworkQueued, To: TaskStateCodeQueued, Trigger: ir.EventTypeCodeReworkAccepted}:     true,
	{From: TaskStateCodeRunning, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeRuntimePinViolated}:      true,
	{From: TaskStateCodeValidating, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeRuntimePinViolated}:   true,
	{From: TaskStateCodeClaimed, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeTaskFailed}:              true,
	{From: TaskStateCodePreparing, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeTaskFailed}:            true,
	{From: TaskStateCodeRunning, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeTaskFailed}:              true,
	{From: TaskStateCodeNeedsInput, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeTaskFailed}:           true,
	{From: TaskStateCodeBlocked, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeTaskFailed}:              true,
	{From: TaskStateCodeValidating, To: TaskStateCodeFailed, Trigger: ir.EventTypeCodeTaskFailed}:           true,
	{From: TaskStateCodeCreated, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled}:        true,
	{From: TaskStateCodeQueued, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled}:         true,
	{From: TaskStateCodeClaimed, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled}:        true,
	{From: TaskStateCodePreparing, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled}:      true,
	{From: TaskStateCodeRunning, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled}:        true,
	{From: TaskStateCodeNeedsInput, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled}:     true,
	{From: TaskStateCodeBlocked, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled}:        true,
	{From: TaskStateCodeValidating, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled}:     true,
	{From: TaskStateCodePatchReady, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled}:     true,
	{From: TaskStateCodeHumanReview, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled}:    true,
	{From: TaskStateCodeReworkQueued, To: TaskStateCodeCancelled, Trigger: ir.EventTypeCodeTaskCancelled}:   true,
	{From: TaskStateCodeRunning, To: TaskStateCodeTimedOut, Trigger: ir.EventTypeCodeTaskTimedOut}:          true,
	{From: TaskStateCodeNeedsInput, To: TaskStateCodeTimedOut, Trigger: ir.EventTypeCodeTaskTimedOut}:       true,
	{From: TaskStateCodeBlocked, To: TaskStateCodeTimedOut, Trigger: ir.EventTypeCodeTaskTimedOut}:          true,
	{From: TaskStateCodeValidating, To: TaskStateCodeTimedOut, Trigger: ir.EventTypeCodeTaskTimedOut}:       true,
	{From: TaskStateCodeHumanReview, To: TaskStateCodeTimedOut, Trigger: ir.EventTypeCodeTaskTimedOut}:      true,
}
