// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package task

import (
	"github.com/teamswyg/riido-contracts/ir"
)

func ValidateTransitionCode(from TaskStateCode, to TaskStateCode, trigger ir.EventTypeCode) bool {
	return taskTransitionCodeAllowed[TaskTransitionCode{From: from, To: to, Trigger: trigger}]
}
