// Code generated by fsm gen from enumgen/enums.lisp; DO NOT EDIT.

package task

import (
	"github.com/teamswyg/riido-contracts/ir"
)

type taskFSMNextStateKey struct {
	From    TaskStateCode
	Trigger ir.EventTypeCode
}

var taskFSMNextStates = map[taskFSMNextStateKey][]TaskStateCode{
	{From: TaskStateCodeCreated, Trigger: ir.EventTypeCodeTaskQueued}:             []TaskStateCode{TaskStateCodeQueued},
	{From: TaskStateCodeCreated, Trigger: ir.EventTypeCodeTaskCancelled}:          []TaskStateCode{TaskStateCodeCancelled},
	{From: TaskStateCodeQueued, Trigger: ir.EventTypeCodeTaskClaimed}:             []TaskStateCode{TaskStateCodeClaimed},
	{From: TaskStateCodeQueued, Trigger: ir.EventTypeCodeTaskCancelled}:           []TaskStateCode{TaskStateCodeCancelled},
	{From: TaskStateCodeClaimed, Trigger: ir.EventTypeCodeWorkdirPreparing}:       []TaskStateCode{TaskStateCodePreparing},
	{From: TaskStateCodeClaimed, Trigger: ir.EventTypeCodeTaskCancelled}:          []TaskStateCode{TaskStateCodeCancelled},
	{From: TaskStateCodeClaimed, Trigger: ir.EventTypeCodeTaskFailed}:             []TaskStateCode{TaskStateCodeFailed},
	{From: TaskStateCodePreparing, Trigger: ir.EventTypeCodeRunStarted}:           []TaskStateCode{TaskStateCodeRunning},
	{From: TaskStateCodePreparing, Trigger: ir.EventTypeCodeBlockerRaised}:        []TaskStateCode{TaskStateCodeBlocked},
	{From: TaskStateCodePreparing, Trigger: ir.EventTypeCodeTaskCancelled}:        []TaskStateCode{TaskStateCodeCancelled},
	{From: TaskStateCodePreparing, Trigger: ir.EventTypeCodeTaskFailed}:           []TaskStateCode{TaskStateCodeFailed},
	{From: TaskStateCodeRunning, Trigger: ir.EventTypeCodeInputRequested}:         []TaskStateCode{TaskStateCodeNeedsInput},
	{From: TaskStateCodeRunning, Trigger: ir.EventTypeCodeBlockerRaised}:          []TaskStateCode{TaskStateCodeBlocked},
	{From: TaskStateCodeRunning, Trigger: ir.EventTypeCodeRunReportedDone}:        []TaskStateCode{TaskStateCodeValidating},
	{From: TaskStateCodeRunning, Trigger: ir.EventTypeCodeTaskCancelled}:          []TaskStateCode{TaskStateCodeCancelled},
	{From: TaskStateCodeRunning, Trigger: ir.EventTypeCodeTaskTimedOut}:           []TaskStateCode{TaskStateCodeTimedOut},
	{From: TaskStateCodeRunning, Trigger: ir.EventTypeCodeRuntimePinViolated}:     []TaskStateCode{TaskStateCodeFailed},
	{From: TaskStateCodeRunning, Trigger: ir.EventTypeCodeTaskFailed}:             []TaskStateCode{TaskStateCodeFailed},
	{From: TaskStateCodeNeedsInput, Trigger: ir.EventTypeCodeInputProvided}:       []TaskStateCode{TaskStateCodeRunning},
	{From: TaskStateCodeNeedsInput, Trigger: ir.EventTypeCodeTaskCancelled}:       []TaskStateCode{TaskStateCodeCancelled},
	{From: TaskStateCodeNeedsInput, Trigger: ir.EventTypeCodeTaskTimedOut}:        []TaskStateCode{TaskStateCodeTimedOut},
	{From: TaskStateCodeNeedsInput, Trigger: ir.EventTypeCodeTaskFailed}:          []TaskStateCode{TaskStateCodeFailed},
	{From: TaskStateCodeBlocked, Trigger: ir.EventTypeCodeBlockerResolved}:        []TaskStateCode{TaskStateCodeRunning},
	{From: TaskStateCodeBlocked, Trigger: ir.EventTypeCodeBlockerResolvedRequeue}: []TaskStateCode{TaskStateCodeQueued},
	{From: TaskStateCodeBlocked, Trigger: ir.EventTypeCodeTaskCancelled}:          []TaskStateCode{TaskStateCodeCancelled},
	{From: TaskStateCodeBlocked, Trigger: ir.EventTypeCodeTaskTimedOut}:           []TaskStateCode{TaskStateCodeTimedOut},
	{From: TaskStateCodeBlocked, Trigger: ir.EventTypeCodeTaskFailed}:             []TaskStateCode{TaskStateCodeFailed},
	{From: TaskStateCodeValidating, Trigger: ir.EventTypeCodeValidationPassed}:    []TaskStateCode{TaskStateCodePatchReady},
	{From: TaskStateCodeValidating, Trigger: ir.EventTypeCodeValidationFailed}:    []TaskStateCode{TaskStateCodeFailed},
	{From: TaskStateCodeValidating, Trigger: ir.EventTypeCodeTaskCancelled}:       []TaskStateCode{TaskStateCodeCancelled},
	{From: TaskStateCodeValidating, Trigger: ir.EventTypeCodeTaskTimedOut}:        []TaskStateCode{TaskStateCodeTimedOut},
	{From: TaskStateCodeValidating, Trigger: ir.EventTypeCodeRuntimePinViolated}:  []TaskStateCode{TaskStateCodeFailed},
	{From: TaskStateCodeValidating, Trigger: ir.EventTypeCodeTaskFailed}:          []TaskStateCode{TaskStateCodeFailed},
	{From: TaskStateCodePatchReady, Trigger: ir.EventTypeCodeReviewRequested}:     []TaskStateCode{TaskStateCodeHumanReview},
	{From: TaskStateCodePatchReady, Trigger: ir.EventTypeCodeAutoApproved}:        []TaskStateCode{TaskStateCodeCompleted},
	{From: TaskStateCodePatchReady, Trigger: ir.EventTypeCodeTaskCancelled}:       []TaskStateCode{TaskStateCodeCancelled},
	{From: TaskStateCodeHumanReview, Trigger: ir.EventTypeCodeHumanApproved}:      []TaskStateCode{TaskStateCodeCompleted},
	{From: TaskStateCodeHumanReview, Trigger: ir.EventTypeCodeHumanRejected}:      []TaskStateCode{TaskStateCodeReworkQueued, TaskStateCodeCancelled},
	{From: TaskStateCodeHumanReview, Trigger: ir.EventTypeCodeTaskCancelled}:      []TaskStateCode{TaskStateCodeCancelled},
	{From: TaskStateCodeHumanReview, Trigger: ir.EventTypeCodeTaskTimedOut}:       []TaskStateCode{TaskStateCodeTimedOut},
	{From: TaskStateCodeReworkQueued, Trigger: ir.EventTypeCodeReworkAccepted}:    []TaskStateCode{TaskStateCodeQueued},
	{From: TaskStateCodeReworkQueued, Trigger: ir.EventTypeCodeTaskCancelled}:     []TaskStateCode{TaskStateCodeCancelled},
}
