// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package task

func (code TaskStateCode) IsKnown() bool {
	_, ok := taskStateStringByCode[code]
	return ok
}

func (code TaskStateCode) StringValue() TaskStateString {
	return taskStateStringByCode[code]
}

func (code TaskStateCode) String() string {
	return string(code.StringValue())
}

func (code TaskStateCode) TaskState() TaskState {
	return TaskState(code.StringValue())
}
