package main

const defaultManifest = "docs/20-domain/ir-schema-versioning.riido.json"

const generatedNotice = "<!-- Generated by go run ./tools/irschemaversioning -write-doc. Do not edit by hand. -->"
