// Code generated by fsm gen from fsmgen/patterns.lisp; DO NOT EDIT.

package fsmmeta

var fSMPatternCodeByString = map[FSMPatternString]FSMPatternCode{
	FSMPatternStringFlat:                FSMPatternCodeFlat,
	FSMPatternStringEventDriven:         FSMPatternCodeEventDriven,
	FSMPatternStringStateDriven:         FSMPatternCodeStateDriven,
	FSMPatternStringExplicitBoundary:    FSMPatternCodeExplicitBoundary,
	FSMPatternStringMultiTerminal:       FSMPatternCodeMultiTerminal,
	FSMPatternStringMultiTargetEvent:    FSMPatternCodeMultiTargetEvent,
	FSMPatternStringSameStateAllowed:    FSMPatternCodeSameStateAllowed,
	FSMPatternStringHierarchical:        FSMPatternCodeHierarchical,
	FSMPatternStringParallel:            FSMPatternCodeParallel,
	FSMPatternStringHistory:             FSMPatternCodeHistory,
	FSMPatternStringGuardedTransition:   FSMPatternCodeGuardedTransition,
	FSMPatternStringEntryAction:         FSMPatternCodeEntryAction,
	FSMPatternStringExitAction:          FSMPatternCodeExitAction,
	FSMPatternStringInternalTransition:  FSMPatternCodeInternalTransition,
	FSMPatternStringEventlessTransition: FSMPatternCodeEventlessTransition,
}
