// Code generated by fsm gen from fsmgen/patterns.lisp; DO NOT EDIT.

package fsmmeta

func AllFSMPatterns() []FSMPattern {
	codes := AllFSMPatternCodes()
	out := make([]FSMPattern, len(codes))
	for index, code := range codes {
		out[index] = code.FSMPattern()
	}
	return out
}
