// Code generated by fsm gen from fsmgen/patterns.lisp; DO NOT EDIT.

package fsmmeta

var allFSMPatternCodes = []FSMPatternCode{
	FSMPatternCodeFlat,
	FSMPatternCodeEventDriven,
	FSMPatternCodeStateDriven,
	FSMPatternCodeExplicitBoundary,
	FSMPatternCodeMultiTerminal,
	FSMPatternCodeMultiTargetEvent,
	FSMPatternCodeSameStateAllowed,
	FSMPatternCodeHierarchical,
	FSMPatternCodeParallel,
	FSMPatternCodeHistory,
	FSMPatternCodeGuardedTransition,
	FSMPatternCodeEntryAction,
	FSMPatternCodeExitAction,
	FSMPatternCodeInternalTransition,
	FSMPatternCodeEventlessTransition,
}

func AllFSMPatternCodes() []FSMPatternCode {
	return append([]FSMPatternCode(nil), allFSMPatternCodes...)
}
