// Code generated by fsm gen from fsmgen/patterns.lisp; DO NOT EDIT.

package fsmmeta

const (
	PatternFlat                FSMPattern = FSMPattern(FSMPatternStringFlat)
	PatternEventDriven         FSMPattern = FSMPattern(FSMPatternStringEventDriven)
	PatternStateDriven         FSMPattern = FSMPattern(FSMPatternStringStateDriven)
	PatternExplicitBoundary    FSMPattern = FSMPattern(FSMPatternStringExplicitBoundary)
	PatternMultiTerminal       FSMPattern = FSMPattern(FSMPatternStringMultiTerminal)
	PatternMultiTargetEvent    FSMPattern = FSMPattern(FSMPatternStringMultiTargetEvent)
	PatternSameStateAllowed    FSMPattern = FSMPattern(FSMPatternStringSameStateAllowed)
	PatternHierarchical        FSMPattern = FSMPattern(FSMPatternStringHierarchical)
	PatternParallel            FSMPattern = FSMPattern(FSMPatternStringParallel)
	PatternHistory             FSMPattern = FSMPattern(FSMPatternStringHistory)
	PatternGuardedTransition   FSMPattern = FSMPattern(FSMPatternStringGuardedTransition)
	PatternEntryAction         FSMPattern = FSMPattern(FSMPatternStringEntryAction)
	PatternExitAction          FSMPattern = FSMPattern(FSMPatternStringExitAction)
	PatternInternalTransition  FSMPattern = FSMPattern(FSMPatternStringInternalTransition)
	PatternEventlessTransition FSMPattern = FSMPattern(FSMPatternStringEventlessTransition)
)
