// Code generated by fsm gen from fsmgen/patterns.lisp; DO NOT EDIT.

package fsmmeta

func (value FSMPattern) Code() FSMPatternCode {
	return ParseFSMPatternCode(string(value))
}

func ParseFSMPatternCode(value string) FSMPatternCode {
	code, ok := fSMPatternCodeByString[FSMPatternString(value)]
	if !ok {
		return FSMPatternCodeUnknown
	}
	return code
}
