// Code generated by fsm gen from fsmgen/patterns.lisp; DO NOT EDIT.

package fsmmeta

const (
	FSMPatternStringFlat                FSMPatternString = "flat"
	FSMPatternStringEventDriven         FSMPatternString = "event-driven"
	FSMPatternStringStateDriven         FSMPatternString = "state-driven"
	FSMPatternStringExplicitBoundary    FSMPatternString = "explicit-boundary"
	FSMPatternStringMultiTerminal       FSMPatternString = "multi-terminal"
	FSMPatternStringMultiTargetEvent    FSMPatternString = "multi-target-event"
	FSMPatternStringSameStateAllowed    FSMPatternString = "same-state-allowed"
	FSMPatternStringHierarchical        FSMPatternString = "hierarchical"
	FSMPatternStringParallel            FSMPatternString = "parallel"
	FSMPatternStringHistory             FSMPatternString = "history"
	FSMPatternStringGuardedTransition   FSMPatternString = "guarded-transition"
	FSMPatternStringEntryAction         FSMPatternString = "entry-action"
	FSMPatternStringExitAction          FSMPatternString = "exit-action"
	FSMPatternStringInternalTransition  FSMPatternString = "internal-transition"
	FSMPatternStringEventlessTransition FSMPatternString = "eventless-transition"
)
