// Code generated by fsm gen from fsmgen/patterns.lisp; DO NOT EDIT.

package fsmmeta

var fSMPatternStringByCode = map[FSMPatternCode]FSMPatternString{
	FSMPatternCodeFlat:                FSMPatternStringFlat,
	FSMPatternCodeEventDriven:         FSMPatternStringEventDriven,
	FSMPatternCodeStateDriven:         FSMPatternStringStateDriven,
	FSMPatternCodeExplicitBoundary:    FSMPatternStringExplicitBoundary,
	FSMPatternCodeMultiTerminal:       FSMPatternStringMultiTerminal,
	FSMPatternCodeMultiTargetEvent:    FSMPatternStringMultiTargetEvent,
	FSMPatternCodeSameStateAllowed:    FSMPatternStringSameStateAllowed,
	FSMPatternCodeHierarchical:        FSMPatternStringHierarchical,
	FSMPatternCodeParallel:            FSMPatternStringParallel,
	FSMPatternCodeHistory:             FSMPatternStringHistory,
	FSMPatternCodeGuardedTransition:   FSMPatternStringGuardedTransition,
	FSMPatternCodeEntryAction:         FSMPatternStringEntryAction,
	FSMPatternCodeExitAction:          FSMPatternStringExitAction,
	FSMPatternCodeInternalTransition:  FSMPatternStringInternalTransition,
	FSMPatternCodeEventlessTransition: FSMPatternStringEventlessTransition,
}
