// Code generated by fsm gen from fsmgen/patterns.lisp; DO NOT EDIT.

package fsmmeta

type FSMPattern string

type FSMPatternCode uint16

type FSMPatternString string

const (
	FSMPatternCodeUnknown FSMPatternCode = iota
	FSMPatternCodeFlat
	FSMPatternCodeEventDriven
	FSMPatternCodeStateDriven
	FSMPatternCodeExplicitBoundary
	FSMPatternCodeMultiTerminal
	FSMPatternCodeMultiTargetEvent
	FSMPatternCodeSameStateAllowed
	FSMPatternCodeHierarchical
	FSMPatternCodeParallel
	FSMPatternCodeHistory
	FSMPatternCodeGuardedTransition
	FSMPatternCodeEntryAction
	FSMPatternCodeExitAction
	FSMPatternCodeInternalTransition
	FSMPatternCodeEventlessTransition
)

const (
	FSMPatternStringFlat                FSMPatternString = "flat"
	FSMPatternStringEventDriven         FSMPatternString = "event-driven"
	FSMPatternStringStateDriven         FSMPatternString = "state-driven"
	FSMPatternStringExplicitBoundary    FSMPatternString = "explicit-boundary"
	FSMPatternStringMultiTerminal       FSMPatternString = "multi-terminal"
	FSMPatternStringMultiTargetEvent    FSMPatternString = "multi-target-event"
	FSMPatternStringSameStateAllowed    FSMPatternString = "same-state-allowed"
	FSMPatternStringHierarchical        FSMPatternString = "hierarchical"
	FSMPatternStringParallel            FSMPatternString = "parallel"
	FSMPatternStringHistory             FSMPatternString = "history"
	FSMPatternStringGuardedTransition   FSMPatternString = "guarded-transition"
	FSMPatternStringEntryAction         FSMPatternString = "entry-action"
	FSMPatternStringExitAction          FSMPatternString = "exit-action"
	FSMPatternStringInternalTransition  FSMPatternString = "internal-transition"
	FSMPatternStringEventlessTransition FSMPatternString = "eventless-transition"
)

const (
	PatternFlat                FSMPattern = FSMPattern(FSMPatternStringFlat)
	PatternEventDriven         FSMPattern = FSMPattern(FSMPatternStringEventDriven)
	PatternStateDriven         FSMPattern = FSMPattern(FSMPatternStringStateDriven)
	PatternExplicitBoundary    FSMPattern = FSMPattern(FSMPatternStringExplicitBoundary)
	PatternMultiTerminal       FSMPattern = FSMPattern(FSMPatternStringMultiTerminal)
	PatternMultiTargetEvent    FSMPattern = FSMPattern(FSMPatternStringMultiTargetEvent)
	PatternSameStateAllowed    FSMPattern = FSMPattern(FSMPatternStringSameStateAllowed)
	PatternHierarchical        FSMPattern = FSMPattern(FSMPatternStringHierarchical)
	PatternParallel            FSMPattern = FSMPattern(FSMPatternStringParallel)
	PatternHistory             FSMPattern = FSMPattern(FSMPatternStringHistory)
	PatternGuardedTransition   FSMPattern = FSMPattern(FSMPatternStringGuardedTransition)
	PatternEntryAction         FSMPattern = FSMPattern(FSMPatternStringEntryAction)
	PatternExitAction          FSMPattern = FSMPattern(FSMPatternStringExitAction)
	PatternInternalTransition  FSMPattern = FSMPattern(FSMPatternStringInternalTransition)
	PatternEventlessTransition FSMPattern = FSMPattern(FSMPatternStringEventlessTransition)
)

func (value FSMPattern) Code() FSMPatternCode {
	return ParseFSMPatternCode(string(value))
}

func ParseFSMPatternCode(value string) FSMPatternCode {
	switch FSMPatternString(value) {
	case FSMPatternStringFlat:
		return FSMPatternCodeFlat
	case FSMPatternStringEventDriven:
		return FSMPatternCodeEventDriven
	case FSMPatternStringStateDriven:
		return FSMPatternCodeStateDriven
	case FSMPatternStringExplicitBoundary:
		return FSMPatternCodeExplicitBoundary
	case FSMPatternStringMultiTerminal:
		return FSMPatternCodeMultiTerminal
	case FSMPatternStringMultiTargetEvent:
		return FSMPatternCodeMultiTargetEvent
	case FSMPatternStringSameStateAllowed:
		return FSMPatternCodeSameStateAllowed
	case FSMPatternStringHierarchical:
		return FSMPatternCodeHierarchical
	case FSMPatternStringParallel:
		return FSMPatternCodeParallel
	case FSMPatternStringHistory:
		return FSMPatternCodeHistory
	case FSMPatternStringGuardedTransition:
		return FSMPatternCodeGuardedTransition
	case FSMPatternStringEntryAction:
		return FSMPatternCodeEntryAction
	case FSMPatternStringExitAction:
		return FSMPatternCodeExitAction
	case FSMPatternStringInternalTransition:
		return FSMPatternCodeInternalTransition
	case FSMPatternStringEventlessTransition:
		return FSMPatternCodeEventlessTransition
	default:
		return FSMPatternCodeUnknown
	}
}

func (code FSMPatternCode) IsKnown() bool {
	return code >= FSMPatternCodeFlat && code <= FSMPatternCodeEventlessTransition
}

func (code FSMPatternCode) StringValue() FSMPatternString {
	switch code {
	case FSMPatternCodeFlat:
		return FSMPatternStringFlat
	case FSMPatternCodeEventDriven:
		return FSMPatternStringEventDriven
	case FSMPatternCodeStateDriven:
		return FSMPatternStringStateDriven
	case FSMPatternCodeExplicitBoundary:
		return FSMPatternStringExplicitBoundary
	case FSMPatternCodeMultiTerminal:
		return FSMPatternStringMultiTerminal
	case FSMPatternCodeMultiTargetEvent:
		return FSMPatternStringMultiTargetEvent
	case FSMPatternCodeSameStateAllowed:
		return FSMPatternStringSameStateAllowed
	case FSMPatternCodeHierarchical:
		return FSMPatternStringHierarchical
	case FSMPatternCodeParallel:
		return FSMPatternStringParallel
	case FSMPatternCodeHistory:
		return FSMPatternStringHistory
	case FSMPatternCodeGuardedTransition:
		return FSMPatternStringGuardedTransition
	case FSMPatternCodeEntryAction:
		return FSMPatternStringEntryAction
	case FSMPatternCodeExitAction:
		return FSMPatternStringExitAction
	case FSMPatternCodeInternalTransition:
		return FSMPatternStringInternalTransition
	case FSMPatternCodeEventlessTransition:
		return FSMPatternStringEventlessTransition
	default:
		return FSMPatternString("")
	}
}

func (code FSMPatternCode) String() string {
	return string(code.StringValue())
}

func (code FSMPatternCode) FSMPattern() FSMPattern {
	return FSMPattern(code.StringValue())
}

func (value FSMPattern) Valid() bool {
	return value.Code().IsKnown()
}

func AllFSMPatternCodes() []FSMPatternCode {
	return []FSMPatternCode{
		FSMPatternCodeFlat,
		FSMPatternCodeEventDriven,
		FSMPatternCodeStateDriven,
		FSMPatternCodeExplicitBoundary,
		FSMPatternCodeMultiTerminal,
		FSMPatternCodeMultiTargetEvent,
		FSMPatternCodeSameStateAllowed,
		FSMPatternCodeHierarchical,
		FSMPatternCodeParallel,
		FSMPatternCodeHistory,
		FSMPatternCodeGuardedTransition,
		FSMPatternCodeEntryAction,
		FSMPatternCodeExitAction,
		FSMPatternCodeInternalTransition,
		FSMPatternCodeEventlessTransition,
	}
}

func AllFSMPatterns() []FSMPattern {
	codes := AllFSMPatternCodes()
	out := make([]FSMPattern, len(codes))
	for index, code := range codes {
		out[index] = code.FSMPattern()
	}
	return out
}
