// Code generated by fsm gen from fsmgen/patterns.lisp; DO NOT EDIT.

package fsmmeta

func (code FSMPatternCode) IsKnown() bool {
	_, ok := fSMPatternStringByCode[code]
	return ok
}

func (code FSMPatternCode) StringValue() FSMPatternString {
	return fSMPatternStringByCode[code]
}

func (code FSMPatternCode) String() string {
	return string(code.StringValue())
}

func (code FSMPatternCode) FSMPattern() FSMPattern {
	return FSMPattern(code.StringValue())
}

func (value FSMPattern) Valid() bool {
	return value.Code().IsKnown()
}
