// Code generated by fsm gen from fsmgen/patterns.lisp; DO NOT EDIT.

package fsmmeta

const (
	FSMPatternCodeUnknown FSMPatternCode = iota
	FSMPatternCodeFlat
	FSMPatternCodeEventDriven
	FSMPatternCodeStateDriven
	FSMPatternCodeExplicitBoundary
	FSMPatternCodeMultiTerminal
	FSMPatternCodeMultiTargetEvent
	FSMPatternCodeSameStateAllowed
	FSMPatternCodeHierarchical
	FSMPatternCodeParallel
	FSMPatternCodeHistory
	FSMPatternCodeGuardedTransition
	FSMPatternCodeEntryAction
	FSMPatternCodeExitAction
	FSMPatternCodeInternalTransition
	FSMPatternCodeEventlessTransition
)
