(enum
  :package ir
  :type EventType
  :code-type EventTypeCode
  :string-type EventTypeString
  :const-prefix Event
  :all AllEventTypes
  :code-all AllEventTypeCodes
  (value EventTaskCreated "TaskCreated" :transition true :native-config forbidden)
  (value EventTaskQueued "TaskQueued" :transition true :native-config forbidden)
  (value EventTaskClaimed "TaskClaimed" :transition true :native-config pre-execute)
  (value EventWorkdirPreparing "WorkdirPreparing" :transition true :native-config pre-execute)
  (value EventRuntimePinned "RuntimePinned" :transition true :native-config pre-execute)
  (value EventRunStarted "RunStarted" :transition true)
  (value EventInputRequested "InputRequested" :transition true)
  (value EventInputProvided "InputProvided" :transition true)
  (value EventBlockerRaised "BlockerRaised" :transition true :native-config phase-dependent)
  (value EventBlockerResolved "BlockerResolved" :transition true :native-config phase-dependent)
  (value EventBlockerResolvedRequeue "BlockerResolvedRequeue" :transition true :native-config phase-dependent)
  (value EventRunReportedDone "RunReportedDone" :transition true)
  (value EventValidationPassed "ValidationPassed" :transition true)
  (value EventValidationFailed "ValidationFailed" :transition true)
  (value EventReviewRequested "ReviewRequested" :transition true)
  (value EventAutoApproved "AutoApproved" :transition true)
  (value EventHumanApproved "HumanApproved" :transition true)
  (value EventHumanRejected "HumanRejected" :transition true)
  (value EventReworkAccepted "ReworkAccepted" :transition true :native-config phase-dependent)
  (value EventTaskCancelled "TaskCancelled" :transition true :native-config phase-dependent)
  (value EventTaskTimedOut "TaskTimedOut" :transition true :native-config phase-dependent)
  (value EventRuntimePinViolated "RuntimePinViolated" :transition true :native-config phase-dependent)
  (value EventTaskFailed "TaskFailed" :transition true :native-config phase-dependent)
  (value EventRuntimeRegistered "RuntimeRegistered" :native-config forbidden)
  (value EventRuntimeRejected "RuntimeRejected" :native-config forbidden)
  (value EventRuntimeFingerprintChanged "RuntimeFingerprintChanged" :native-config forbidden)
  (value EventCapabilityReevaluated "CapabilityReevaluated" :native-config forbidden)
  (value EventLeaseInvalidated "LeaseInvalidated" :native-config forbidden)
  (value EventRuntimeHandshakeOK "RuntimeHandshakeOK" :native-config pre-execute)
  (value EventTextDelta "TextDelta")
  (value EventReasoningDelta "ReasoningDelta")
  (value EventToolCallStarted "ToolCallStarted")
  (value EventToolCallFinished "ToolCallFinished")
  (value EventFileChanged "FileChanged")
  (value EventCommandStarted "CommandStarted")
  (value EventCommandFinished "CommandFinished")
  (value EventSessionPinned "SessionPinned")
  (value EventApprovalRequested "ApprovalRequested")
  (value EventApprovalResolved "ApprovalResolved")
  (value EventStatusUpdate "StatusUpdate")
  (value EventUsageDelta "UsageDelta")
  (value EventLogLine "LogLine")
  (value EventProviderUnknownEvent "ProviderUnknownEvent")
  (value EventValidationStarted "ValidationStarted")
  (value EventValidationRuleExecuted "ValidationRuleExecuted")
  (value EventWorkdirCreated "WorkdirCreated" :native-config pre-execute)
  (value EventNativeConfigInjected "NativeConfigInjected")
  (value EventWorkdirArchived "WorkdirArchived")
  (value EventConfigTemplateReinjected "ConfigTemplateReinjected")
  (value EventPolicyBundleLoaded "PolicyBundleLoaded" :native-config forbidden)
  (value EventPolicyBundleSwitched "PolicyBundleSwitched" :native-config forbidden)
  (value EventPolicyViolationDetected "PolicyViolationDetected")
  (value EventSecretsScopeIssued "SecretsScopeIssued")
  (value EventSecretsScopeRevoked "SecretsScopeRevoked")
  (value EventUpgradeDetected "UpgradeDetected" :native-config forbidden)
  (value EventUpgradePolicyReevaluated "UpgradePolicyReevaluated" :native-config forbidden)
  (value EventDrainStarted "DrainStarted" :native-config forbidden)
  (value EventDrainTimedOut "DrainTimedOut" :native-config forbidden)
  (value EventTaskHandedOff "TaskHandedOff")
  (value EventCorrection "Correction")
  (value EventOperatorNote "OperatorNote")
  (value EventSnapshot "Snapshot"))
