package main

const (
	schemaVersion         = "riido-contracts-context-map.v1"
	defaultManifest       = "docs/20-domain/context-map.riido.json"
	evidenceSchemaVersion = "riido-context-map-evidence.v1"
	generatedMarker       = "<!-- Code generated by go run ./tools/contextmap write-doc; DO NOT EDIT. -->"
)
