package main

const (
	schemaVersion         = "riido-contracts-migration-ledger.v1"
	defaultManifest       = "docs/migration/contracts.riido.json"
	evidenceSchemaVersion = "riido-migration-ledger-evidence.v1"
	generatedMarker       = "<!-- Code generated by go run ./tools/migrationdocs write-doc; DO NOT EDIT. -->"
)
