package main

import (
	"bytes"
	"fmt"
)

func writeHeader(b *bytes.Buffer, packageName string) {
	fmt.Fprintf(b, "// Code generated by %s from %s; DO NOT EDIT.\n\n", generatedBy, sourcePath)
	fmt.Fprintf(b, "package %s\n\n", packageName)
}
