package main

const (
	defaultManifestPath = "docs/20-domain/ai-agent-visibility.riido.json"
	generatedNotice     = "<!-- Generated by go run ./tools/aiagentvisibility -write-doc. DO NOT EDIT. -->"
)
