package main

const (
	defaultManifestPath = "docs/20-domain/ai-agent-api-surface.riido.json"
	generatedNotice     = "<!-- Generated by go run ./tools/aiagentapisurface -write-doc. DO NOT EDIT. -->"
)
