package main

const (
	defaultManifestPath = "docs/20-domain/ai-agent-task-assignment.riido.json"
	generatedNotice     = "<!-- Generated by go run ./tools/aiagenttaskassignment -write-doc. DO NOT EDIT. -->"
)
