// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package ir

func (code EventTypeCode) IsKnown() bool {
	_, ok := eventTypeStringByCode[code]
	return ok
}

func (code EventTypeCode) StringValue() EventTypeString {
	return eventTypeStringByCode[code]
}

func (code EventTypeCode) String() string {
	return string(code.StringValue())
}

func (code EventTypeCode) EventType() EventType {
	return EventType(code.StringValue())
}
