// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package ir

func (code EventTypeCode) IsTransition() bool {
	switch code {
	case EventTypeCodeTaskCreated, EventTypeCodeTaskQueued, EventTypeCodeTaskClaimed, EventTypeCodeWorkdirPreparing, EventTypeCodeRuntimePinned, EventTypeCodeRunStarted, EventTypeCodeInputRequested, EventTypeCodeInputProvided, EventTypeCodeBlockerRaised, EventTypeCodeBlockerResolved, EventTypeCodeBlockerResolvedRequeue, EventTypeCodeRunReportedDone, EventTypeCodeValidationPassed, EventTypeCodeValidationFailed, EventTypeCodeReviewRequested, EventTypeCodeAutoApproved, EventTypeCodeHumanApproved, EventTypeCodeHumanRejected, EventTypeCodeReworkAccepted, EventTypeCodeTaskCancelled, EventTypeCodeTaskTimedOut, EventTypeCodeRuntimePinViolated, EventTypeCodeTaskFailed:
		return true
	default:
		return false
	}
}

func (value EventType) IsTransition() bool {
	return value.Code().IsTransition()
}

func (code EventTypeCode) NativeConfigRequirement() NativeConfigRequirement {
	switch code {
	case EventTypeCodeTaskClaimed, EventTypeCodeWorkdirPreparing, EventTypeCodeRuntimePinned, EventTypeCodeRuntimeHandshakeOK, EventTypeCodeWorkdirCreated:
		return NativeConfigOptionalPreExecute
	case EventTypeCodeBlockerRaised, EventTypeCodeBlockerResolved, EventTypeCodeBlockerResolvedRequeue, EventTypeCodeReworkAccepted, EventTypeCodeTaskCancelled, EventTypeCodeTaskTimedOut, EventTypeCodeRuntimePinViolated, EventTypeCodeTaskFailed:
		return NativeConfigPhaseDependent
	case EventTypeCodeTaskCreated, EventTypeCodeTaskQueued, EventTypeCodeRuntimeRegistered, EventTypeCodeRuntimeRejected, EventTypeCodeRuntimeFingerprintChanged, EventTypeCodeCapabilityReevaluated, EventTypeCodeLeaseInvalidated, EventTypeCodePolicyBundleLoaded, EventTypeCodePolicyBundleSwitched, EventTypeCodeUpgradeDetected, EventTypeCodeUpgradePolicyReevaluated, EventTypeCodeDrainStarted, EventTypeCodeDrainTimedOut:
		return NativeConfigForbidden
	default:
		return NativeConfigRequired
	}
}

func (value EventType) NativeConfigRequirement() NativeConfigRequirement {
	return value.Code().NativeConfigRequirement()
}
