// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package ir

type EventTypeCode uint16

type EventTypeString string

const (
	EventTypeCodeUnknown EventTypeCode = iota
	EventTypeCodeTaskCreated
	EventTypeCodeTaskQueued
	EventTypeCodeTaskClaimed
	EventTypeCodeWorkdirPreparing
	EventTypeCodeRuntimePinned
	EventTypeCodeRunStarted
	EventTypeCodeInputRequested
	EventTypeCodeInputProvided
	EventTypeCodeBlockerRaised
	EventTypeCodeBlockerResolved
	EventTypeCodeBlockerResolvedRequeue
	EventTypeCodeRunReportedDone
	EventTypeCodeValidationPassed
	EventTypeCodeValidationFailed
	EventTypeCodeReviewRequested
	EventTypeCodeAutoApproved
	EventTypeCodeHumanApproved
	EventTypeCodeHumanRejected
	EventTypeCodeReworkAccepted
	EventTypeCodeTaskCancelled
	EventTypeCodeTaskTimedOut
	EventTypeCodeRuntimePinViolated
	EventTypeCodeTaskFailed
	EventTypeCodeRuntimeRegistered
	EventTypeCodeRuntimeRejected
	EventTypeCodeRuntimeFingerprintChanged
	EventTypeCodeCapabilityReevaluated
	EventTypeCodeLeaseInvalidated
	EventTypeCodeRuntimeHandshakeOK
	EventTypeCodeTextDelta
	EventTypeCodeReasoningDelta
	EventTypeCodeToolCallStarted
	EventTypeCodeToolCallFinished
	EventTypeCodeFileChanged
	EventTypeCodeCommandStarted
	EventTypeCodeCommandFinished
	EventTypeCodeSessionPinned
	EventTypeCodeApprovalRequested
	EventTypeCodeApprovalResolved
	EventTypeCodeStatusUpdate
	EventTypeCodeUsageDelta
	EventTypeCodeLogLine
	EventTypeCodeProviderUnknownEvent
	EventTypeCodeValidationStarted
	EventTypeCodeValidationRuleExecuted
	EventTypeCodeWorkdirCreated
	EventTypeCodeNativeConfigInjected
	EventTypeCodeWorkdirArchived
	EventTypeCodeConfigTemplateReinjected
	EventTypeCodePolicyBundleLoaded
	EventTypeCodePolicyBundleSwitched
	EventTypeCodePolicyViolationDetected
	EventTypeCodeSecretsScopeIssued
	EventTypeCodeSecretsScopeRevoked
	EventTypeCodeUpgradeDetected
	EventTypeCodeUpgradePolicyReevaluated
	EventTypeCodeDrainStarted
	EventTypeCodeDrainTimedOut
	EventTypeCodeTaskHandedOff
	EventTypeCodeCorrection
	EventTypeCodeOperatorNote
	EventTypeCodeSnapshot
)

const (
	EventTypeStringTaskCreated               EventTypeString = "TaskCreated"
	EventTypeStringTaskQueued                EventTypeString = "TaskQueued"
	EventTypeStringTaskClaimed               EventTypeString = "TaskClaimed"
	EventTypeStringWorkdirPreparing          EventTypeString = "WorkdirPreparing"
	EventTypeStringRuntimePinned             EventTypeString = "RuntimePinned"
	EventTypeStringRunStarted                EventTypeString = "RunStarted"
	EventTypeStringInputRequested            EventTypeString = "InputRequested"
	EventTypeStringInputProvided             EventTypeString = "InputProvided"
	EventTypeStringBlockerRaised             EventTypeString = "BlockerRaised"
	EventTypeStringBlockerResolved           EventTypeString = "BlockerResolved"
	EventTypeStringBlockerResolvedRequeue    EventTypeString = "BlockerResolvedRequeue"
	EventTypeStringRunReportedDone           EventTypeString = "RunReportedDone"
	EventTypeStringValidationPassed          EventTypeString = "ValidationPassed"
	EventTypeStringValidationFailed          EventTypeString = "ValidationFailed"
	EventTypeStringReviewRequested           EventTypeString = "ReviewRequested"
	EventTypeStringAutoApproved              EventTypeString = "AutoApproved"
	EventTypeStringHumanApproved             EventTypeString = "HumanApproved"
	EventTypeStringHumanRejected             EventTypeString = "HumanRejected"
	EventTypeStringReworkAccepted            EventTypeString = "ReworkAccepted"
	EventTypeStringTaskCancelled             EventTypeString = "TaskCancelled"
	EventTypeStringTaskTimedOut              EventTypeString = "TaskTimedOut"
	EventTypeStringRuntimePinViolated        EventTypeString = "RuntimePinViolated"
	EventTypeStringTaskFailed                EventTypeString = "TaskFailed"
	EventTypeStringRuntimeRegistered         EventTypeString = "RuntimeRegistered"
	EventTypeStringRuntimeRejected           EventTypeString = "RuntimeRejected"
	EventTypeStringRuntimeFingerprintChanged EventTypeString = "RuntimeFingerprintChanged"
	EventTypeStringCapabilityReevaluated     EventTypeString = "CapabilityReevaluated"
	EventTypeStringLeaseInvalidated          EventTypeString = "LeaseInvalidated"
	EventTypeStringRuntimeHandshakeOK        EventTypeString = "RuntimeHandshakeOK"
	EventTypeStringTextDelta                 EventTypeString = "TextDelta"
	EventTypeStringReasoningDelta            EventTypeString = "ReasoningDelta"
	EventTypeStringToolCallStarted           EventTypeString = "ToolCallStarted"
	EventTypeStringToolCallFinished          EventTypeString = "ToolCallFinished"
	EventTypeStringFileChanged               EventTypeString = "FileChanged"
	EventTypeStringCommandStarted            EventTypeString = "CommandStarted"
	EventTypeStringCommandFinished           EventTypeString = "CommandFinished"
	EventTypeStringSessionPinned             EventTypeString = "SessionPinned"
	EventTypeStringApprovalRequested         EventTypeString = "ApprovalRequested"
	EventTypeStringApprovalResolved          EventTypeString = "ApprovalResolved"
	EventTypeStringStatusUpdate              EventTypeString = "StatusUpdate"
	EventTypeStringUsageDelta                EventTypeString = "UsageDelta"
	EventTypeStringLogLine                   EventTypeString = "LogLine"
	EventTypeStringProviderUnknownEvent      EventTypeString = "ProviderUnknownEvent"
	EventTypeStringValidationStarted         EventTypeString = "ValidationStarted"
	EventTypeStringValidationRuleExecuted    EventTypeString = "ValidationRuleExecuted"
	EventTypeStringWorkdirCreated            EventTypeString = "WorkdirCreated"
	EventTypeStringNativeConfigInjected      EventTypeString = "NativeConfigInjected"
	EventTypeStringWorkdirArchived           EventTypeString = "WorkdirArchived"
	EventTypeStringConfigTemplateReinjected  EventTypeString = "ConfigTemplateReinjected"
	EventTypeStringPolicyBundleLoaded        EventTypeString = "PolicyBundleLoaded"
	EventTypeStringPolicyBundleSwitched      EventTypeString = "PolicyBundleSwitched"
	EventTypeStringPolicyViolationDetected   EventTypeString = "PolicyViolationDetected"
	EventTypeStringSecretsScopeIssued        EventTypeString = "SecretsScopeIssued"
	EventTypeStringSecretsScopeRevoked       EventTypeString = "SecretsScopeRevoked"
	EventTypeStringUpgradeDetected           EventTypeString = "UpgradeDetected"
	EventTypeStringUpgradePolicyReevaluated  EventTypeString = "UpgradePolicyReevaluated"
	EventTypeStringDrainStarted              EventTypeString = "DrainStarted"
	EventTypeStringDrainTimedOut             EventTypeString = "DrainTimedOut"
	EventTypeStringTaskHandedOff             EventTypeString = "TaskHandedOff"
	EventTypeStringCorrection                EventTypeString = "Correction"
	EventTypeStringOperatorNote              EventTypeString = "OperatorNote"
	EventTypeStringSnapshot                  EventTypeString = "Snapshot"
)

const (
	EventTaskCreated               EventType = EventType(EventTypeStringTaskCreated)
	EventTaskQueued                EventType = EventType(EventTypeStringTaskQueued)
	EventTaskClaimed               EventType = EventType(EventTypeStringTaskClaimed)
	EventWorkdirPreparing          EventType = EventType(EventTypeStringWorkdirPreparing)
	EventRuntimePinned             EventType = EventType(EventTypeStringRuntimePinned)
	EventRunStarted                EventType = EventType(EventTypeStringRunStarted)
	EventInputRequested            EventType = EventType(EventTypeStringInputRequested)
	EventInputProvided             EventType = EventType(EventTypeStringInputProvided)
	EventBlockerRaised             EventType = EventType(EventTypeStringBlockerRaised)
	EventBlockerResolved           EventType = EventType(EventTypeStringBlockerResolved)
	EventBlockerResolvedRequeue    EventType = EventType(EventTypeStringBlockerResolvedRequeue)
	EventRunReportedDone           EventType = EventType(EventTypeStringRunReportedDone)
	EventValidationPassed          EventType = EventType(EventTypeStringValidationPassed)
	EventValidationFailed          EventType = EventType(EventTypeStringValidationFailed)
	EventReviewRequested           EventType = EventType(EventTypeStringReviewRequested)
	EventAutoApproved              EventType = EventType(EventTypeStringAutoApproved)
	EventHumanApproved             EventType = EventType(EventTypeStringHumanApproved)
	EventHumanRejected             EventType = EventType(EventTypeStringHumanRejected)
	EventReworkAccepted            EventType = EventType(EventTypeStringReworkAccepted)
	EventTaskCancelled             EventType = EventType(EventTypeStringTaskCancelled)
	EventTaskTimedOut              EventType = EventType(EventTypeStringTaskTimedOut)
	EventRuntimePinViolated        EventType = EventType(EventTypeStringRuntimePinViolated)
	EventTaskFailed                EventType = EventType(EventTypeStringTaskFailed)
	EventRuntimeRegistered         EventType = EventType(EventTypeStringRuntimeRegistered)
	EventRuntimeRejected           EventType = EventType(EventTypeStringRuntimeRejected)
	EventRuntimeFingerprintChanged EventType = EventType(EventTypeStringRuntimeFingerprintChanged)
	EventCapabilityReevaluated     EventType = EventType(EventTypeStringCapabilityReevaluated)
	EventLeaseInvalidated          EventType = EventType(EventTypeStringLeaseInvalidated)
	EventRuntimeHandshakeOK        EventType = EventType(EventTypeStringRuntimeHandshakeOK)
	EventTextDelta                 EventType = EventType(EventTypeStringTextDelta)
	EventReasoningDelta            EventType = EventType(EventTypeStringReasoningDelta)
	EventToolCallStarted           EventType = EventType(EventTypeStringToolCallStarted)
	EventToolCallFinished          EventType = EventType(EventTypeStringToolCallFinished)
	EventFileChanged               EventType = EventType(EventTypeStringFileChanged)
	EventCommandStarted            EventType = EventType(EventTypeStringCommandStarted)
	EventCommandFinished           EventType = EventType(EventTypeStringCommandFinished)
	EventSessionPinned             EventType = EventType(EventTypeStringSessionPinned)
	EventApprovalRequested         EventType = EventType(EventTypeStringApprovalRequested)
	EventApprovalResolved          EventType = EventType(EventTypeStringApprovalResolved)
	EventStatusUpdate              EventType = EventType(EventTypeStringStatusUpdate)
	EventUsageDelta                EventType = EventType(EventTypeStringUsageDelta)
	EventLogLine                   EventType = EventType(EventTypeStringLogLine)
	EventProviderUnknownEvent      EventType = EventType(EventTypeStringProviderUnknownEvent)
	EventValidationStarted         EventType = EventType(EventTypeStringValidationStarted)
	EventValidationRuleExecuted    EventType = EventType(EventTypeStringValidationRuleExecuted)
	EventWorkdirCreated            EventType = EventType(EventTypeStringWorkdirCreated)
	EventNativeConfigInjected      EventType = EventType(EventTypeStringNativeConfigInjected)
	EventWorkdirArchived           EventType = EventType(EventTypeStringWorkdirArchived)
	EventConfigTemplateReinjected  EventType = EventType(EventTypeStringConfigTemplateReinjected)
	EventPolicyBundleLoaded        EventType = EventType(EventTypeStringPolicyBundleLoaded)
	EventPolicyBundleSwitched      EventType = EventType(EventTypeStringPolicyBundleSwitched)
	EventPolicyViolationDetected   EventType = EventType(EventTypeStringPolicyViolationDetected)
	EventSecretsScopeIssued        EventType = EventType(EventTypeStringSecretsScopeIssued)
	EventSecretsScopeRevoked       EventType = EventType(EventTypeStringSecretsScopeRevoked)
	EventUpgradeDetected           EventType = EventType(EventTypeStringUpgradeDetected)
	EventUpgradePolicyReevaluated  EventType = EventType(EventTypeStringUpgradePolicyReevaluated)
	EventDrainStarted              EventType = EventType(EventTypeStringDrainStarted)
	EventDrainTimedOut             EventType = EventType(EventTypeStringDrainTimedOut)
	EventTaskHandedOff             EventType = EventType(EventTypeStringTaskHandedOff)
	EventCorrection                EventType = EventType(EventTypeStringCorrection)
	EventOperatorNote              EventType = EventType(EventTypeStringOperatorNote)
	EventSnapshot                  EventType = EventType(EventTypeStringSnapshot)
)

func (value EventType) Code() EventTypeCode {
	return ParseEventTypeCode(string(value))
}

func ParseEventTypeCode(value string) EventTypeCode {
	switch EventTypeString(value) {
	case EventTypeStringTaskCreated:
		return EventTypeCodeTaskCreated
	case EventTypeStringTaskQueued:
		return EventTypeCodeTaskQueued
	case EventTypeStringTaskClaimed:
		return EventTypeCodeTaskClaimed
	case EventTypeStringWorkdirPreparing:
		return EventTypeCodeWorkdirPreparing
	case EventTypeStringRuntimePinned:
		return EventTypeCodeRuntimePinned
	case EventTypeStringRunStarted:
		return EventTypeCodeRunStarted
	case EventTypeStringInputRequested:
		return EventTypeCodeInputRequested
	case EventTypeStringInputProvided:
		return EventTypeCodeInputProvided
	case EventTypeStringBlockerRaised:
		return EventTypeCodeBlockerRaised
	case EventTypeStringBlockerResolved:
		return EventTypeCodeBlockerResolved
	case EventTypeStringBlockerResolvedRequeue:
		return EventTypeCodeBlockerResolvedRequeue
	case EventTypeStringRunReportedDone:
		return EventTypeCodeRunReportedDone
	case EventTypeStringValidationPassed:
		return EventTypeCodeValidationPassed
	case EventTypeStringValidationFailed:
		return EventTypeCodeValidationFailed
	case EventTypeStringReviewRequested:
		return EventTypeCodeReviewRequested
	case EventTypeStringAutoApproved:
		return EventTypeCodeAutoApproved
	case EventTypeStringHumanApproved:
		return EventTypeCodeHumanApproved
	case EventTypeStringHumanRejected:
		return EventTypeCodeHumanRejected
	case EventTypeStringReworkAccepted:
		return EventTypeCodeReworkAccepted
	case EventTypeStringTaskCancelled:
		return EventTypeCodeTaskCancelled
	case EventTypeStringTaskTimedOut:
		return EventTypeCodeTaskTimedOut
	case EventTypeStringRuntimePinViolated:
		return EventTypeCodeRuntimePinViolated
	case EventTypeStringTaskFailed:
		return EventTypeCodeTaskFailed
	case EventTypeStringRuntimeRegistered:
		return EventTypeCodeRuntimeRegistered
	case EventTypeStringRuntimeRejected:
		return EventTypeCodeRuntimeRejected
	case EventTypeStringRuntimeFingerprintChanged:
		return EventTypeCodeRuntimeFingerprintChanged
	case EventTypeStringCapabilityReevaluated:
		return EventTypeCodeCapabilityReevaluated
	case EventTypeStringLeaseInvalidated:
		return EventTypeCodeLeaseInvalidated
	case EventTypeStringRuntimeHandshakeOK:
		return EventTypeCodeRuntimeHandshakeOK
	case EventTypeStringTextDelta:
		return EventTypeCodeTextDelta
	case EventTypeStringReasoningDelta:
		return EventTypeCodeReasoningDelta
	case EventTypeStringToolCallStarted:
		return EventTypeCodeToolCallStarted
	case EventTypeStringToolCallFinished:
		return EventTypeCodeToolCallFinished
	case EventTypeStringFileChanged:
		return EventTypeCodeFileChanged
	case EventTypeStringCommandStarted:
		return EventTypeCodeCommandStarted
	case EventTypeStringCommandFinished:
		return EventTypeCodeCommandFinished
	case EventTypeStringSessionPinned:
		return EventTypeCodeSessionPinned
	case EventTypeStringApprovalRequested:
		return EventTypeCodeApprovalRequested
	case EventTypeStringApprovalResolved:
		return EventTypeCodeApprovalResolved
	case EventTypeStringStatusUpdate:
		return EventTypeCodeStatusUpdate
	case EventTypeStringUsageDelta:
		return EventTypeCodeUsageDelta
	case EventTypeStringLogLine:
		return EventTypeCodeLogLine
	case EventTypeStringProviderUnknownEvent:
		return EventTypeCodeProviderUnknownEvent
	case EventTypeStringValidationStarted:
		return EventTypeCodeValidationStarted
	case EventTypeStringValidationRuleExecuted:
		return EventTypeCodeValidationRuleExecuted
	case EventTypeStringWorkdirCreated:
		return EventTypeCodeWorkdirCreated
	case EventTypeStringNativeConfigInjected:
		return EventTypeCodeNativeConfigInjected
	case EventTypeStringWorkdirArchived:
		return EventTypeCodeWorkdirArchived
	case EventTypeStringConfigTemplateReinjected:
		return EventTypeCodeConfigTemplateReinjected
	case EventTypeStringPolicyBundleLoaded:
		return EventTypeCodePolicyBundleLoaded
	case EventTypeStringPolicyBundleSwitched:
		return EventTypeCodePolicyBundleSwitched
	case EventTypeStringPolicyViolationDetected:
		return EventTypeCodePolicyViolationDetected
	case EventTypeStringSecretsScopeIssued:
		return EventTypeCodeSecretsScopeIssued
	case EventTypeStringSecretsScopeRevoked:
		return EventTypeCodeSecretsScopeRevoked
	case EventTypeStringUpgradeDetected:
		return EventTypeCodeUpgradeDetected
	case EventTypeStringUpgradePolicyReevaluated:
		return EventTypeCodeUpgradePolicyReevaluated
	case EventTypeStringDrainStarted:
		return EventTypeCodeDrainStarted
	case EventTypeStringDrainTimedOut:
		return EventTypeCodeDrainTimedOut
	case EventTypeStringTaskHandedOff:
		return EventTypeCodeTaskHandedOff
	case EventTypeStringCorrection:
		return EventTypeCodeCorrection
	case EventTypeStringOperatorNote:
		return EventTypeCodeOperatorNote
	case EventTypeStringSnapshot:
		return EventTypeCodeSnapshot
	default:
		return EventTypeCodeUnknown
	}
}

func (code EventTypeCode) IsKnown() bool {
	return code >= EventTypeCodeTaskCreated && code <= EventTypeCodeSnapshot
}

func (code EventTypeCode) StringValue() EventTypeString {
	switch code {
	case EventTypeCodeTaskCreated:
		return EventTypeStringTaskCreated
	case EventTypeCodeTaskQueued:
		return EventTypeStringTaskQueued
	case EventTypeCodeTaskClaimed:
		return EventTypeStringTaskClaimed
	case EventTypeCodeWorkdirPreparing:
		return EventTypeStringWorkdirPreparing
	case EventTypeCodeRuntimePinned:
		return EventTypeStringRuntimePinned
	case EventTypeCodeRunStarted:
		return EventTypeStringRunStarted
	case EventTypeCodeInputRequested:
		return EventTypeStringInputRequested
	case EventTypeCodeInputProvided:
		return EventTypeStringInputProvided
	case EventTypeCodeBlockerRaised:
		return EventTypeStringBlockerRaised
	case EventTypeCodeBlockerResolved:
		return EventTypeStringBlockerResolved
	case EventTypeCodeBlockerResolvedRequeue:
		return EventTypeStringBlockerResolvedRequeue
	case EventTypeCodeRunReportedDone:
		return EventTypeStringRunReportedDone
	case EventTypeCodeValidationPassed:
		return EventTypeStringValidationPassed
	case EventTypeCodeValidationFailed:
		return EventTypeStringValidationFailed
	case EventTypeCodeReviewRequested:
		return EventTypeStringReviewRequested
	case EventTypeCodeAutoApproved:
		return EventTypeStringAutoApproved
	case EventTypeCodeHumanApproved:
		return EventTypeStringHumanApproved
	case EventTypeCodeHumanRejected:
		return EventTypeStringHumanRejected
	case EventTypeCodeReworkAccepted:
		return EventTypeStringReworkAccepted
	case EventTypeCodeTaskCancelled:
		return EventTypeStringTaskCancelled
	case EventTypeCodeTaskTimedOut:
		return EventTypeStringTaskTimedOut
	case EventTypeCodeRuntimePinViolated:
		return EventTypeStringRuntimePinViolated
	case EventTypeCodeTaskFailed:
		return EventTypeStringTaskFailed
	case EventTypeCodeRuntimeRegistered:
		return EventTypeStringRuntimeRegistered
	case EventTypeCodeRuntimeRejected:
		return EventTypeStringRuntimeRejected
	case EventTypeCodeRuntimeFingerprintChanged:
		return EventTypeStringRuntimeFingerprintChanged
	case EventTypeCodeCapabilityReevaluated:
		return EventTypeStringCapabilityReevaluated
	case EventTypeCodeLeaseInvalidated:
		return EventTypeStringLeaseInvalidated
	case EventTypeCodeRuntimeHandshakeOK:
		return EventTypeStringRuntimeHandshakeOK
	case EventTypeCodeTextDelta:
		return EventTypeStringTextDelta
	case EventTypeCodeReasoningDelta:
		return EventTypeStringReasoningDelta
	case EventTypeCodeToolCallStarted:
		return EventTypeStringToolCallStarted
	case EventTypeCodeToolCallFinished:
		return EventTypeStringToolCallFinished
	case EventTypeCodeFileChanged:
		return EventTypeStringFileChanged
	case EventTypeCodeCommandStarted:
		return EventTypeStringCommandStarted
	case EventTypeCodeCommandFinished:
		return EventTypeStringCommandFinished
	case EventTypeCodeSessionPinned:
		return EventTypeStringSessionPinned
	case EventTypeCodeApprovalRequested:
		return EventTypeStringApprovalRequested
	case EventTypeCodeApprovalResolved:
		return EventTypeStringApprovalResolved
	case EventTypeCodeStatusUpdate:
		return EventTypeStringStatusUpdate
	case EventTypeCodeUsageDelta:
		return EventTypeStringUsageDelta
	case EventTypeCodeLogLine:
		return EventTypeStringLogLine
	case EventTypeCodeProviderUnknownEvent:
		return EventTypeStringProviderUnknownEvent
	case EventTypeCodeValidationStarted:
		return EventTypeStringValidationStarted
	case EventTypeCodeValidationRuleExecuted:
		return EventTypeStringValidationRuleExecuted
	case EventTypeCodeWorkdirCreated:
		return EventTypeStringWorkdirCreated
	case EventTypeCodeNativeConfigInjected:
		return EventTypeStringNativeConfigInjected
	case EventTypeCodeWorkdirArchived:
		return EventTypeStringWorkdirArchived
	case EventTypeCodeConfigTemplateReinjected:
		return EventTypeStringConfigTemplateReinjected
	case EventTypeCodePolicyBundleLoaded:
		return EventTypeStringPolicyBundleLoaded
	case EventTypeCodePolicyBundleSwitched:
		return EventTypeStringPolicyBundleSwitched
	case EventTypeCodePolicyViolationDetected:
		return EventTypeStringPolicyViolationDetected
	case EventTypeCodeSecretsScopeIssued:
		return EventTypeStringSecretsScopeIssued
	case EventTypeCodeSecretsScopeRevoked:
		return EventTypeStringSecretsScopeRevoked
	case EventTypeCodeUpgradeDetected:
		return EventTypeStringUpgradeDetected
	case EventTypeCodeUpgradePolicyReevaluated:
		return EventTypeStringUpgradePolicyReevaluated
	case EventTypeCodeDrainStarted:
		return EventTypeStringDrainStarted
	case EventTypeCodeDrainTimedOut:
		return EventTypeStringDrainTimedOut
	case EventTypeCodeTaskHandedOff:
		return EventTypeStringTaskHandedOff
	case EventTypeCodeCorrection:
		return EventTypeStringCorrection
	case EventTypeCodeOperatorNote:
		return EventTypeStringOperatorNote
	case EventTypeCodeSnapshot:
		return EventTypeStringSnapshot
	default:
		return EventTypeString("")
	}
}

func (code EventTypeCode) String() string {
	return string(code.StringValue())
}

func (code EventTypeCode) EventType() EventType {
	return EventType(code.StringValue())
}

func (value EventType) Valid() bool {
	return value.Code().IsKnown()
}

func AllEventTypeCodes() []EventTypeCode {
	return []EventTypeCode{
		EventTypeCodeTaskCreated,
		EventTypeCodeTaskQueued,
		EventTypeCodeTaskClaimed,
		EventTypeCodeWorkdirPreparing,
		EventTypeCodeRuntimePinned,
		EventTypeCodeRunStarted,
		EventTypeCodeInputRequested,
		EventTypeCodeInputProvided,
		EventTypeCodeBlockerRaised,
		EventTypeCodeBlockerResolved,
		EventTypeCodeBlockerResolvedRequeue,
		EventTypeCodeRunReportedDone,
		EventTypeCodeValidationPassed,
		EventTypeCodeValidationFailed,
		EventTypeCodeReviewRequested,
		EventTypeCodeAutoApproved,
		EventTypeCodeHumanApproved,
		EventTypeCodeHumanRejected,
		EventTypeCodeReworkAccepted,
		EventTypeCodeTaskCancelled,
		EventTypeCodeTaskTimedOut,
		EventTypeCodeRuntimePinViolated,
		EventTypeCodeTaskFailed,
		EventTypeCodeRuntimeRegistered,
		EventTypeCodeRuntimeRejected,
		EventTypeCodeRuntimeFingerprintChanged,
		EventTypeCodeCapabilityReevaluated,
		EventTypeCodeLeaseInvalidated,
		EventTypeCodeRuntimeHandshakeOK,
		EventTypeCodeTextDelta,
		EventTypeCodeReasoningDelta,
		EventTypeCodeToolCallStarted,
		EventTypeCodeToolCallFinished,
		EventTypeCodeFileChanged,
		EventTypeCodeCommandStarted,
		EventTypeCodeCommandFinished,
		EventTypeCodeSessionPinned,
		EventTypeCodeApprovalRequested,
		EventTypeCodeApprovalResolved,
		EventTypeCodeStatusUpdate,
		EventTypeCodeUsageDelta,
		EventTypeCodeLogLine,
		EventTypeCodeProviderUnknownEvent,
		EventTypeCodeValidationStarted,
		EventTypeCodeValidationRuleExecuted,
		EventTypeCodeWorkdirCreated,
		EventTypeCodeNativeConfigInjected,
		EventTypeCodeWorkdirArchived,
		EventTypeCodeConfigTemplateReinjected,
		EventTypeCodePolicyBundleLoaded,
		EventTypeCodePolicyBundleSwitched,
		EventTypeCodePolicyViolationDetected,
		EventTypeCodeSecretsScopeIssued,
		EventTypeCodeSecretsScopeRevoked,
		EventTypeCodeUpgradeDetected,
		EventTypeCodeUpgradePolicyReevaluated,
		EventTypeCodeDrainStarted,
		EventTypeCodeDrainTimedOut,
		EventTypeCodeTaskHandedOff,
		EventTypeCodeCorrection,
		EventTypeCodeOperatorNote,
		EventTypeCodeSnapshot,
	}
}

func AllEventTypes() []EventType {
	codes := AllEventTypeCodes()
	out := make([]EventType, len(codes))
	for index, code := range codes {
		out[index] = code.EventType()
	}
	return out
}

func (code EventTypeCode) IsTransition() bool {
	switch code {
	case EventTypeCodeTaskCreated, EventTypeCodeTaskQueued, EventTypeCodeTaskClaimed, EventTypeCodeWorkdirPreparing, EventTypeCodeRuntimePinned, EventTypeCodeRunStarted, EventTypeCodeInputRequested, EventTypeCodeInputProvided, EventTypeCodeBlockerRaised, EventTypeCodeBlockerResolved, EventTypeCodeBlockerResolvedRequeue, EventTypeCodeRunReportedDone, EventTypeCodeValidationPassed, EventTypeCodeValidationFailed, EventTypeCodeReviewRequested, EventTypeCodeAutoApproved, EventTypeCodeHumanApproved, EventTypeCodeHumanRejected, EventTypeCodeReworkAccepted, EventTypeCodeTaskCancelled, EventTypeCodeTaskTimedOut, EventTypeCodeRuntimePinViolated, EventTypeCodeTaskFailed:
		return true
	default:
		return false
	}
}

func (value EventType) IsTransition() bool {
	return value.Code().IsTransition()
}

func (code EventTypeCode) NativeConfigRequirement() NativeConfigRequirement {
	switch code {
	case EventTypeCodeTaskClaimed, EventTypeCodeWorkdirPreparing, EventTypeCodeRuntimePinned, EventTypeCodeRuntimeHandshakeOK, EventTypeCodeWorkdirCreated:
		return NativeConfigOptionalPreExecute
	case EventTypeCodeBlockerRaised, EventTypeCodeBlockerResolved, EventTypeCodeBlockerResolvedRequeue, EventTypeCodeReworkAccepted, EventTypeCodeTaskCancelled, EventTypeCodeTaskTimedOut, EventTypeCodeRuntimePinViolated, EventTypeCodeTaskFailed:
		return NativeConfigPhaseDependent
	case EventTypeCodeTaskCreated, EventTypeCodeTaskQueued, EventTypeCodeRuntimeRegistered, EventTypeCodeRuntimeRejected, EventTypeCodeRuntimeFingerprintChanged, EventTypeCodeCapabilityReevaluated, EventTypeCodeLeaseInvalidated, EventTypeCodePolicyBundleLoaded, EventTypeCodePolicyBundleSwitched, EventTypeCodeUpgradeDetected, EventTypeCodeUpgradePolicyReevaluated, EventTypeCodeDrainStarted, EventTypeCodeDrainTimedOut:
		return NativeConfigForbidden
	default:
		return NativeConfigRequired
	}
}

func (value EventType) NativeConfigRequirement() NativeConfigRequirement {
	return value.Code().NativeConfigRequirement()
}
