// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package ir

func AllEventTypeCodes() []EventTypeCode {
	return append([]EventTypeCode(nil), eventTypeAllCodes...)
}

func AllEventTypes() []EventType {
	codes := AllEventTypeCodes()
	out := make([]EventType, len(codes))
	for index, code := range codes {
		out[index] = code.EventType()
	}
	return out
}
