// Code generated by enum gen from enumgen/enums.lisp; DO NOT EDIT.

package ir

func (value EventType) Code() EventTypeCode {
	return ParseEventTypeCode(string(value))
}

func ParseEventTypeCode(value string) EventTypeCode {
	code, ok := eventTypeCodeByString[EventTypeString(value)]
	if !ok {
		return EventTypeCodeUnknown
	}
	return code
}
