package main

const (
	defaultManifest = "docs/20-domain/provider-capability.riido.json"
	manifestSchema  = "riido-contracts-provider-capability-doc.v1"
	evidenceSchema  = "riido-contracts-provider-capability-evidence.v1"
	generatedNotice = "<!-- Generated by go run ./tools/providercapability -write-doc. Do not edit by hand. -->"
)
