package main

const (
	manifestSchema  = "riido-contracts-api-projection-doc.v1"
	evidenceSchema  = "riido-contracts-api-projection-result.v1"
	defaultManifest = "docs/20-domain/api-contract-projection.riido.json"
	generatedNotice = "<!-- Generated by go run ./tools/apicontractdoc -write-doc. Do not edit by hand. -->"
)
