package main

const (
	schemaVersion         = "riido-domain-docs-index.v1"
	defaultManifest       = "docs/20-domain/README.riido.json"
	evidenceSchemaVersion = "riido-domain-docs-index-evidence.v1"
	generatedMarker       = "<!-- Code generated by go run ./tools/domaindocs write-doc; DO NOT EDIT. -->"
)
