package main

const (
	schemaVersion   = "riido-contracts-open-questions.v1"
	evidenceVersion = "riido-contracts-open-questions-result.v1"
	defaultManifest = "docs/50-roadmap/open-questions.riido.json"
	generatedNotice = "<!-- Generated by go run ./tools/openquestions -write-doc. Do not edit by hand. -->"
)
