package main

const (
	manifestSchema  = "riido-contracts-assignment-polling-doc.v1"
	evidenceSchema  = "riido-contracts-assignment-polling-result.v1"
	defaultManifest = "docs/20-domain/assignment-polling.riido.json"
	defaultContract = "assignment/assignment_contract.riido.json"
	generatedNotice = "<!-- Generated by go run ./tools/assignmentcontract -write-doc. Do not edit by hand. -->"

	stateSchema       = "riido-ai-server-contract-assignment-state.v1"
	pollActionSchema  = "riido-ai-server-contract-poll-action.v1"
	taskEventSchema   = "riido-ai-server-contract-task-event.v1"
	executionIDSchema = "riido-ai-server-contract-execution-identity.v1"
	approvalSchema    = "riido-ai-server-contract-approval.v1"
	payloadSchema     = "riido-ai-server-contract-assignment-payload-field.v1"
)
