package main

const (
	manifestSchema  = "riido-contracts-assignment-polling-doc.v1"
	evidenceSchema  = "riido-contracts-assignment-polling-result.v1"
	defaultManifest = "docs/20-domain/assignment-polling.riido.json"
	defaultContract = "assignment/assignment_contract.riido.json"
	generatedNotice = "<!-- Generated by go run ./tools/assignmentcontract -write-doc. Do not edit by hand. -->"
)
