package main

const (
	schemaVersion   = "riido-contracts-executable-knowledge-coverage.v1"
	evidenceVersion = "riido-contracts-executable-knowledge-coverage-result.v1"
	defaultManifest = "docs/executable-knowledge.riido.json"
	generatedNotice = "<!-- Generated by go run ./tools/knowledgecoverage -write-doc. Do not edit by hand. -->"
)
