package main

const (
	schemaVersion         = "riido-contracts-architecture.v1"
	defaultManifest       = "docs/30-architecture/contracts-architecture.riido.json"
	evidenceSchemaVersion = "riido-architecture-docs-evidence.v1"
	generatedMarker       = "<!-- Code generated by go run ./tools/architecturedocs write-doc; DO NOT EDIT. -->"
)
