package main

const (
	defaultManifestPath = "docs/20-domain/distribution-host-integration.riido.json"
	generatedNotice     = "<!-- Generated by go run ./tools/hostintegrationdoc -write-doc. DO NOT EDIT. -->"
)
