package main

const (
	defaultManifestPath = "docs/20-domain/ai-agent-configuration.riido.json"
	generatedNotice     = "<!-- Generated by go run ./tools/aiagentconfiguration -write-doc. DO NOT EDIT. -->"
)
