package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"unicode"

	"github.com/teamswyg/riido-contracts/assignment"
	"github.com/teamswyg/riido-contracts/ir"
	"github.com/teamswyg/riido-contracts/task"
)

func taskStateCodeRef(code task.TaskStateCode) string {
	return "TaskStateCode" + pascalCodeSuffix(code.String())
}

func eventTypeCodeRef(code ir.EventTypeCode) string {
	return "ir.EventTypeCode" + pascalCodeSuffix(code.String())
}

func assignmentStateCodeRef(code assignment.AssignmentStateCode) string {
	return "AssignmentStateCode" + pascalCodeSuffix(code.String())
}

func pascalCodeSuffix(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool {
		return r == '_' || r == '-' || unicode.IsSpace(r)
	})
	for index, part := range parts {
		if part == "" {
			continue
		}
		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		parts[index] = string(runes)
	}
	return strings.Join(parts, "")
}

func mermaidNode(value string) string {
	if value == "" {
		return "unknown"
	}
	var b strings.Builder
	for index, r := range value {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			if index == 0 {
				b.WriteRune(unicode.ToUpper(r))
			} else {
				b.WriteRune(r)
			}
			continue
		}
		b.WriteByte('_')
	}
	return b.String()
}

func writeHeader(b *bytes.Buffer, packageName string) {
	fmt.Fprintf(b, "// Code generated by %s from %s; DO NOT EDIT.\n\n", generatedBy, sourcePath)
	fmt.Fprintf(b, "package %s\n\n", packageName)
}

func formatSource(name string, source []byte) ([]byte, error) {
	out, err := format.Source(source)
	if err != nil {
		return nil, fmt.Errorf("format %s: %w\n%s", name, err, source)
	}
	return out, nil
}
