package main

import (
	"strings"
	"testing"
)

func TestRenderManifestCarriesHumanPhrase(t *testing.T) {
	body := renderManifest(minimalManifest(t))
	if !strings.Contains(body, "Code generated by go run ./tools/ssotdeps render") {
		t.Fatalf("missing generated marker: %q", body)
	}
	if !strings.Contains(body, minimalFact().HumanDocPhrase) {
		t.Fatalf("missing human phrase: %q", body)
	}
}
