package main

import (
	"fmt"
	"strings"
)

func renderManifest(m manifest) string {
	var b strings.Builder
	b.WriteString("# SSOT Dependency Map\n\n")
	b.WriteString("<!-- Code generated by go run ./tools/ssotdeps render; DO NOT EDIT. -->\n\n")
	fmt.Fprintf(&b, "> Riido task: %s\n\n", markdownCell(m.RiidoTask))
	b.WriteString("This projection is generated from `ssot-dependency-map.riido.json`.\n")
	b.WriteString("Regenerate it with `go run ./tools/ssotdeps render`.\n\n")
	renderRule(&b)
	renderFacts(&b, m.Facts)
	renderRepoDependencies(&b, m.RepoDependencies)
	renderLoop(&b)
	return b.String()
}

func renderRule(b *strings.Builder) {
	b.WriteString("## Rule\n\n")
	b.WriteString("One durable fact has one owner. Downstream repositories may repeat ")
	b.WriteString("that fact only as local execution, projection, or harness behavior.\n\n")
	b.WriteString("A lower-layer contradiction must be recorded locally, escalated to ")
	b.WriteString("the owning SSOT when meaning changes, then regenerated downstream.\n\n")
}
