package main

const (
	defaultManifestPath   = "docs/20-domain/ai-agent-policy.riido.json"
	generatedNotice       = "<!-- Generated by go run ./tools/aiagentpolicy -write-doc. DO NOT EDIT. -->"
	schemaVersion         = "riido-ai-agent-policy.v1"
	evidenceSchemaVersion = "riido-ai-agent-policy-evidence.v1"
)
