package main

const (
	defaultManifestPath = "docs/20-domain/ai-agent-assigned-profile-map.riido.json"
	generatedNotice     = "<!-- Generated by go run ./tools/aiagentprofilemap -write-doc. DO NOT EDIT. -->"
)
