package main

const (
	defaultManifestPath = "docs/20-domain/ai-agent-onboarding.riido.json"
	generatedNotice     = "<!-- Generated by go run ./tools/aiagentonboarding -write-doc. DO NOT EDIT. -->"
)
