package main

const (
	docSchemaVersion = "riido-contracts-progress-message-catalog-doc.v1"
	evidenceVersion  = "riido-contracts-progress-message-catalog-result.v1"
	docManifestPath  = "docs/20-domain/progress-message-catalog.riido.json"
	generatedNotice  = "<!-- Generated by go run ./tools/progressmessage verify -write-doc. Do not edit by hand. -->"
)
